### ISSUE TITLE
Community Focus

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#10]
Our [/about page](http://www.mozillascience.org/about) now lists contributors to the science lab. What can do to help surface our awesome community of makers and contributors?

Right now, to be list on the page users must have one of:
1. Lead a project in Collaborate
2. Be a facilitator at an event (just MozFest 2014 and Toronto Code Sprint for now)
3. Written a blog post for us (doesn't include guest posts -- probably should)

What else can we do surface our contributors? Should we list *everyone* who logs in here?

**Comment by BillMills** [comment]
Thinking out loud:

For other categories, what about contributors to other repos not on Collaborate? (I'm looking at study groups and possibly code review). Secret second option might just be to put those on Collaborate :)

For more events, is there a way we can fold in registering regular events? There are a bunch of people doing study groups I'd like to recognize and promote. But, this may not really be appropriate, seeing as the framing here is specifically MSL contributors, and not just people doing cool stuff.

I'd like to set the bar for representation at the tiniest contribution (not just login) - that way, we give a little nudge to get involved. In which case, what about forum posters? I think keeping conversations going is definitely a legit way to participate.
