### ISSUE TITLE
Convey benefits of membership

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#103]
Just noticing that it's not immediately clear from the homepage, for example, why someone should "join" MSL (as opposed to just browsing the site, using the resources, finding a Study Group, etc.)

Can @acabunoc @kaythaney @zee-moz @stephwright @auremoser weigh in on the rationale for joining? Wondering if a brief "Why join?" page/lightbox would be useful?

**Comment by hannahkane** [comment]
Might also discuss how the experience might change for authenticated users. Are there any changes on the current site, @acabunoc ?

**Comment by auremoser** [comment]
Yeah, the "why join" modal seems to make sense. I believe they joined to login and participate in blog posts, get listed as participants in events, and (now) edit and add their own events though I'm not sure anyone does this.

**Comment by hannahkane** [comment]
Closing. Assuming we'll address this when we are ready to add authentication.
