### ISSUE TITLE
List of resources

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#104]
Compile a list of all the resources we want on the site and where on the site we want them to appear. I've set up a table to work off of but feel free to adapt it:
https://docs.google.com/a/mozilla.com/spreadsheets/d/1aQhmnDO4zYt24sD8ItYeesbAn2TUiHzKyllSkzs4VN0/edit?usp=sharing

These wireframes are a work in progress but we can reference them as a starting point: https://redpen.io/p/eb9d7534bcf4dfcc17
Particularly the Study Group page: https://redpen.io/ow3163da6caa22acde
Resources page: https://redpen.io/dr1a6e5c79b466e524
Project page: https://redpen.io/jc2e62ed8f6f3f6ef5

@zee-moz, I think you would probably be best person to do this?
cc @hannahkane @acabunoc @stephwright @auremoser @kaythaney

**Comment by kristinashu** [comment]
Sounds like @auremoser is working on this?

**Comment by auremoser** [comment]
Sure, I can give the more broad resources catalog a shot!

**Comment by acabunoc** [comment]
@auremoser is working on this!

**Comment by kristinashu** [comment]
Thanks! Looks like a bunch of resources were added to the speadsheet. We can edit as we go but I have enough to get started.
