### ISSUE TITLE
Copy for Projects page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#105]
We need to find a concise way to introduce what the Projects section is all about - what is it for, who is it for, why it is good... And then we can link to the resources about working in the open, github... 
Please add any other thoughts.

Here is a high level wireframe of the page: https://redpen.io/jc2e62ed8f6f3f6ef5

We can add to the home page copy deck https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit

**Comment by hannahkane** [comment]
Thanks for filing this ticket, @kristinashu.

@kaythaney - are you able to take this task on? Or would it be helpful for me or someone else to do a first draft for you to respond to?

**Comment by kaythaney** [comment]
happy to help, but would love for @acabunoc's input on this.

On Fri, Mar 25, 2016 at 2:44 PM, hannahkane <notifications@github.com>
wrote:

> Thanks for filing this ticket, @kristinashu
> <https://github.com/kristinashu>.
>
> @kaythaney <https://github.com/kaythaney> - are you able to take this
> task on? Or would it be helpful for me or someone else to do a first draft
> for you to respond to?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/issues/105#issuecomment-201416164>
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by acabunoc** [comment]
I can take a first pass at this!

**Comment by hannahkane** [comment]
Thanks, @acabunoc! Do you have a sense of when in the heartbeat you'll get to this?

Wondering if it's possible to get @kristinashu a high-level overview of the copy early in the heartbeat, even if it's just to signal whether you think something will significantly impact the page layout - e.g. "there will actually be a short paragraph introducing the Contribute to a Project section" or something like that.

**Comment by acabunoc** [comment]
I've blocked off part of tomorrow afternoon for this - I can probably think about page layout earlier

**Comment by kristinashu** [comment]
Thanks @acabunoc! 

Here's a wireframe to show how the copy is looking: https://redpen.io/jc2e62ed8f6f3f6ef5

Could everyone please take a look at the [copy doc](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#heading=h.xm1qmbkhves4) and me know if they think a particular tagline or intro is working better than another?

We also still need copy for the intro to open source section. Something along the lines of What is open source? How to get started? and How it helps science? 
You can see placeholder text in the wireframe:
![projects5 2x](https://cloud.githubusercontent.com/assets/1068783/14252473/60c011a0-fa3c-11e5-912f-dfd3ee86508c.jpg)

cc @hannahkane @kaythaney @auremoser @zee-moz @stephwright

**Comment by hannahkane** [comment]
Thanks, @kristinashu. I added some [copy suggestions](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#heading=h.spcspaqt4ij0) for the three bits (what is open source? how to get started? how it helps science?

But will definitely need refining from Science team, who may not be able to get to this this week, given their work week.
