### ISSUE TITLE
README needs more explanation...

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#108]
A few points could use tweaking or explanation:

1. Step 4 indicates setting a PORT, but there's no placeholder for this value in `env.dist`. It also seems to just default to 5000, so no editing should be necessary.
2. It looks like MongoDB requires setup, but there are no instructions.
3. There are empty AWS values, but again I'm not sure if these are needed.
4. The specific permissions granted for the GitHub personal access token aren't indicated. I'd like to limit it just to the specifically needed permissions and not allow everything.

I'm happy to create a PR if someone can fill me in on the specifics... (CC: @acabunoc @alicoding)

**Comment by acabunoc** [comment]
Thanks @gvn! Happy for a PR, but I think the plan for the new site is to start from scratch since we're separating out the API.

**Comment by acabunoc** [comment]
To answer the individual points:

1. yes, that's a good point
2. true
3. we use s3 to store photos users upload with their projects on /collaborate
4. That's a good idea, there is a scope associated with the GitHub authentication (https://github.com/mozillascience/site/blob/master/app.js#L332) once they log in

**Comment by gvn** [comment]
Oh! Well disregard if we're starting fresh! :+1:

**Comment by acabunoc** [comment]
closing! this was for the old site
