### ISSUE TITLE
Comps for all event pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#117]
Wireframes: https://redpen.io/p/eb9d7534bcf4dfcc17
Without search/sort/filter functionality.

**Comment by kristinashu** [comment]
With the exception of mobile, initial comps are for all these pages are in redpen https://redpen.io/p/eb9d7534bcf4dfcc17

**Comment by hannahkane** [comment]
Looking really good!

**Comment by kristinashu** [comment]
Added a mobile example to redpen.

@xmatthewx and or @vazquez could I please get a design review on the event pages https://redpen.io/p/eb9d7534bcf4dfcc17

**Comment by kristinashu** [comment]
Thanks for the feedback @xmatthewx and @vazquez! 

I'll be making the updates now.

**Comment by kristinashu** [comment]
Science team, please add any thoughts or feedback you might have https://redpen.io/p/eb9d7534bcf4dfcc17

Thanks! @acabunoc @kaythaney @auremoser @zee-moz @stephwright
