### ISSUE TITLE
Comps for fellowship pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#118]
Based on wireframes: https://redpen.io/p/eb9d7534bcf4dfcc17

**Comment by kristinashu** [comment]
@xmatthewx could you please do a design review on the fellowships pages: https://redpen.io/p/eb9d7534bcf4dfcc17

**Comment by xmatthewx** [comment]
Review. Things looked good. I noted in redpen that a few layout details need a comp to show how they'll work on smaller screens or narrow browsers. 

I think we also need a comp for the drop-down menu on large screens, with info on how it works (hover/click/dismiss). I also wonder about the hierarchy: fellowships is hidden under programs and less visibility than resources.

**Comment by kristinashu** [comment]
Thanks @xmatthewx! Redpen is being buggy and I can only see the start of your comments in the notifications, and can't see them in the comps. Bit of follow up here:
- I'll try the comps with left aligned text instead of centered
- Gavin and Alan seem pretty good with responsive states so our plan is that they build it then I do a design pass (with the expectation that there will be some tweaks needed)
- For the dropdown menu, do you mean the main nav? It's almost finished on staging http://science-mozilla-org-staging.herokuapp.com/ 
- Fellowships is only really important for a short time each year (during application period) and to a pretty niche group so we didn't think it warranted a spot in the main level nav. Having the CTA banner on the homepage is our way of highlighting it during that time. I think the Resources section is actually quite important, it is valuable for a much wider audience and also often what new visitors are looking for. Having said that, the IA was tricky to to work out and it is something we definitely want to test post launch.

**Comment by kristinashu** [comment]
Oooh I can see the comps in redpen now!

**Comment by xmatthewx** [comment]
Great. That all makes sense. 

As we start thinking about universal nav patterns, we'll want good guidelines so we don't invite excess content in subnav that could be better integrated or cut.

**Comment by hannahkane** [comment]
@kristinashu - is it ok to either close this or take it out of the milestone now, so we can close April 22?

**Comment by kristinashu** [comment]
Closing!
