### ISSUE TITLE
Comps for Blog

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#119]
- [x] Individual page
 - [x] List view of all blogs

Use Onesie! This should be generic enough to apply to other blogs.

**Individual Post**
Each post, no matter what site it lives on, will have...
* Title
* Date and time published & updated
* Author (and link to posts by that author)
* Full text
* List of tags (each linked to related articles)
* List of categories that it belongs to (each linked to category views)
* Discussion & comments section
* Social buttons? Share on Twitter, Fb, etc?

**List View**
Search field
Paginated list, ordered by reverse chron
* Hyperlinked title
* Date and time published/updated
* Author
* Truncated text

**Comment by kristinashu** [comment]
@flukeout I think you started a blog template a little while ago? Would you be interested in doing the science blog, or just sharing the work you've done so far?

**Comment by kristinashu** [comment]
This is linked to the audit work - Identify shared needs for blogs https://github.com/MozillaFoundation/plan/issues/687

**Comment by kristinashu** [comment]
@xmatthewx any chance you could do a design review on the blog pages: https://redpen.io/p/eb9d7534bcf4dfcc17

**Comment by xmatthewx** [comment]
Looks good. A few notes in redpen, but nothing too big.

**Comment by kristinashu** [comment]
Thanks, I've commented and made a few updates.
