### ISSUE TITLE
Build front end for Events pages and functionality

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#120]
Styling of the three main tabs
 https://redpen.io/vhc355394a8e93c08b (all 1.1 content) (without search/sort/filter)

**Comment by gvn** [comment]
Let's start by building this sans-tabswitcher (just as long pages of content).

Once I complete the tabswitcher we can drop it in!

**Comment by kristinashu** [comment]
@alanmoo maybe you're working on it but I wanted to make sure it's clear that events at the top of the landing page should only be upcoming events. All past events are in the archive section.

I see some past events are showing up with an image:
<img width="536" alt="screen shot 2016-05-06 at 10 14 30 am" src="https://cloud.githubusercontent.com/assets/1068783/15080838/c4933f08-1374-11e6-8cea-a3bdcfcc56aa.png">

**Comment by acabunoc** [comment]
Also (again @alanmoo you may be working on this), but the event pages should have the slug in the url (not the event id number) -- this will help us with forwarding old pages on the new site

**Comment by alanmoo** [comment]
Yeah, @gideonthomas @alicoding and I had a convo about the slug already. I need to take a look at the API for events and see what we have/if more tickets need filing
