### ISSUE TITLE
Comps for Resources page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#126]
Based on wireframes: https://redpen.io/p/eb9d7534bcf4dfcc17

**Comment by kristinashu** [comment]
Initial resource page comp: https://redpen.io/dr1a6e5c79b466e524

We had hoped to not need filters but I think they are necessary. We already have 27 resources which gets overwhelming and very long on one page so I've added some placeholder filters in.

Categories are being worked on: https://docs.google.com/a/mozilla.com/spreadsheets/d/1aQhmnDO4zYt24sD8ItYeesbAn2TUiHzKyllSkzs4VN0/edit?usp=sharing

![jpgs_resources 2x copy](https://cloud.githubusercontent.com/assets/1068783/14869469/7fe4c40a-0c88-11e6-95c7-8d1879a03857.jpg)

**Comment by hannahkane** [comment]
I think this looks nice, @kristinashu. 

I updated the [content doc](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#) with some places where it looks like we need to fill in copy. Flagging @acabunoc and @auremoser to help with that, if you haven't already discussed it.

**Comment by kristinashu** [comment]
Thanks for the copy, I've added it to the comp and opened a new ticket for finalizing the categories - Finalize resource categories #269

![jpgs_resources 2x copy](https://cloud.githubusercontent.com/assets/1068783/14929313/bb6a00c8-0e11-11e6-8ea6-cb32c5b1e650.jpg)
