### ISSUE TITLE
Build members pages

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#134]
https://redpen.io/pq5fb24849ad3b7634 (6.0, 6.1)

Assume data will be there by the time this needs to be built

- [ ] #311 Home page
- [ ] #312 Member profile

**Comment by hannahkane** [comment]
No longer a requirement for launch, so removing from May 20 mileston

**Comment by hannahkane** [comment]
Blocked by authentication / people being able to add themselves

Related to #553, which may be the start of this

**Comment by hannahkane** [comment]
Closing in lieu of https://github.com/mozilla/science.mozilla.org/projects/2
