### ISSUE TITLE
Design files for dev

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#139]
@gvn @alanmoo still working on all of these but here are the most recent files:

Redpen of wireframes and comps (replacing wireframes with comps as I do them):
https://redpen.io/p/eb9d7534bcf4dfcc17

URLs:
https://redpen.io/gpdfe4cfad5fac095e

Illustrator files (working file - will continue to update):
https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLQk50UDhVcGFkYVk/view?usp=sharing

Copy doc with link URLs (WIP):
https://docs.google.com/a/mozilla.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit?usp=sharing

Exported assets (will add more as I go):
https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLUm1HZExlOUVkcFk&usp=sharing

**Comment by gvn** [comment]
Thanks!

**Comment by gvn** [comment]
Actually, @kristinashu looks like that AI is missing a bunch of assets:

eg:

<img width="496" alt="screen shot 2016-04-11 at 2 02 09 pm" src="https://cloud.githubusercontent.com/assets/206379/14442363/2322f724-ffee-11e5-9ec6-9774c964de13.png">

**Comment by kristinashu** [comment]
@gvn I've embedded the images and made a few updates https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLWVlPNkt2NEpSMnc/view?usp=sharing

**Comment by kristinashu** [comment]
@gvn @alanmoo these are all the colors used on the site (with the exception of the "sprinkles"):
<img width="492" alt="screen shot 2016-04-11 at 3 54 00 pm" src="https://cloud.githubusercontent.com/assets/1068783/14444991/63951bd8-fffe-11e5-8072-5c07b1435fd3.png">
(illustrator is being annoying with colors and some how changing them slightly and randomly on me so I just want to make sure you get the right onesie colors)

**Comment by kristinashu** [comment]
Sorry, it's a work in progress so illustrator file keeps getting updated. Here's the latest https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLU0tNODZneHIyWDQ/view?usp=sharing

**Comment by alanmoo** [comment]
@kristinashu Can you export the logo text and image as a single svg?

**Comment by kristinashu** [comment]
@alanmoo unfortunately the logo has some crazy overlay effects and gradients that don't show up in the svg format. It's not ideal but would you want the entire thing as a png?

**Comment by alanmoo** [comment]
Hrm...yeah, I'll take that at 2x for now and maybe we can look into the logo deeper in the future.

**Comment by kristinashu** [comment]
Here it is: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLd0loV0Jsc19zNlk/view?usp=sharing
![logo-mozillascience 2x](https://cloud.githubusercontent.com/assets/1068783/14501229/2e01e9b2-015a-11e6-9d60-201becffcb45.png)

Yeah, updating colors of the logo is a whole can of worms I'm not ready to get into!

**Comment by alanmoo** [comment]
Can I also get the SVG for hamburger/close icons in the menu?

**Comment by alanmoo** [comment]
Oh and the arrow next to "Programs"?

**Comment by kristinashu** [comment]
Here's the burger and close svgs https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLSzRKcWZFVE5DR28&usp=sharing

The arrow is from font awesome https://fortawesome.github.io/Font-Awesome/cheatsheet/
fa-angle-down [&#xf107;]
fa-angle-up [&#xf106;]

**Comment by gvn** [comment]
@kristinashu How much are you planning to use Font Awesome? Do you think you might use more than 5-10 glyphs from it?

**Comment by kristinashu** [comment]
Actually, there probably won't be very many... here's an svg of the arrow https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLQkx4aENQbU1mTnM/view?usp=sharing

**Comment by gvn** [comment]
Ok cool. We're not planning on including it so far because it's quite large if we're only using a few glyphs. We can grab SVGs from it a la carte though...

**Comment by kristinashu** [comment]
Closing this ticket. I'll keep adding files to the folder as they come up but ping me if you need anything.
