### ISSUE TITLE
build Box with colored shadow (see homepage comp) component

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#148]
<img width="426" alt="screen shot 2016-04-11 at 12 57 45 pm" src="https://cloud.githubusercontent.com/assets/206379/14440527/0c5cfc32-ffe5-11e5-9ab4-58965038a684.png">

**Comment by acabunoc** [comment]
is this done?

**Comment by gvn** [comment]
Yeah, this is the ShadowBox component.
