### ISSUE TITLE
Build breadcrumb

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#150]
<img width="195" alt="screen shot 2016-04-11 at 12 59 39 pm" src="https://cloud.githubusercontent.com/assets/206379/14440561/451de0a4-ffe5-11e5-815c-eb1da1e26306.png">

**Comment by kristinashu** [comment]
I think we can forget about breadcrumbs. @gvn feel free to close this ticket if you agree.

**Comment by gvn** [comment]
👍
