### ISSUE TITLE
Homepage - What's New 

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#154]
- [x] build general layout

**Comment by mmhyamin** [comment]
Do you have any design?

**Comment by gvn** [comment]
Hi @mmhyamin. We do have design, but this will be built by our internal team as it's time sensitive.

Stay tuned though, we should have tickets open for contributors in a month or so. Thanks!

**Comment by kristinashu** [comment]
Box shadowy thing is looking good! Mobile seems fine for now - I think you could move the carousel to 'phase 2' if you wanted. 

Opened a ticket for minor design tweaks https://github.com/mozilla/science.mozilla.org/issues/233
