### ISSUE TITLE
Project pages front end

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#165]
I may be doing this wrong
![wrong](https://cloud.githubusercontent.com/assets/1682681/14442646/ed0d1b40-0008-11e6-8867-7948e2b97282.gif)

(Zenhub is required to see more data attached to this, apparently...)

**Comment by alanmoo** [comment]
I may be doing this wrong
![wrong](https://cloud.githubusercontent.com/assets/1682681/14442646/ed0d1b40-0008-11e6-8867-7948e2b97282.gif)

**Comment by acabunoc** [comment]
Both 'Add project' and 'Thank you page' can wait if time is tight since we're delaying authentication till after launch. (Both pages need auth)

**Comment by hannahkane** [comment]
Closing this parent ticket, in lieu of new [Project project](https://github.com/mozilla/science.mozilla.org/projects/1) heh.
