### ISSUE TITLE
Set up Heroku pipeline

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#169]
It would be great if PR's could automatically generate a Heroku URL. I tried to set up a pipeline in Heroku (https://dashboard.heroku.com/pipelines/new) but I don't have admin access to this repo. @cadecairos do you?

https://github.com/integrations/heroku-review-apps

**Comment by cadecairos** [comment]
I've [created a pipeline](https://dashboard.heroku.com/pipelines/07f01c87-8d30-4856-97e7-2cc584d0b4c4), but we need a fully configured staging app to inherit configuration from.

**Comment by alanmoo** [comment]
Great, thanks. I’ll work on that, as I should have appropriate permissions.
