### ISSUE TITLE
Comp for event landing page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#170]
https://redpen.io/vhc355394a8e93c08b

**Comment by kristinashu** [comment]
Initial comp is done: https://redpen.io/aq0c17cb0774ab55bd

Suggesting we could do filter functionality and possibly even archive of events as a phase 2.

![04_events 2x](https://cloud.githubusercontent.com/assets/1068783/14479244/63f9d89c-00d1-11e6-91fd-3226f567bfc9.jpg)

**Comment by hannahkane** [comment]
+1 to @kristinashu's suggestion to move filtering and archive to Phase 2, but checking with @acabunoc to see if that's acceptable.

**Comment by acabunoc** [comment]
yes!

**Comment by kristinashu** [comment]
Yes to holding off on filtering but in Redpen we talked about the need to keep archived events because they are often linked in.
