### ISSUE TITLE
Comp for simple event page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#171]
https://redpen.io/vxab11f78998c91e29

**Comment by kristinashu** [comment]
Initial comps:
Phase 1: https://redpen.io/upad1a641838872f52
![04_events-simple 2x](https://cloud.githubusercontent.com/assets/1068783/14479340/3c16af2a-00d2-11e6-8193-255cc04806d6.jpg)

Phase 2: with facilitators and participants https://redpen.io/vxab11f78998c91e29
![04_events-simple 2x](https://cloud.githubusercontent.com/assets/1068783/14479356/5986e872-00d2-11e6-9cbc-cc8e8c7d7e03.jpg)

**Comment by hannahkane** [comment]
Looks great. Just noting that on similar pages on the Teach site, we've embedded the etherpad into the page itself (see https://teach.mozilla.org/community/curriculum-workshop). This was at the request of  program staff.

Is there a benefit to standardizing this one way or another?

**Comment by kristinashu** [comment]
Thanks for pointing that out. I'm not totally sold on the embedded etherpad because I worry about it taking up a lot of space (and load time) on some of the longer/more complex event pages. Aligning with Teach would be great but I think focusing on aligning all the different science events is more important and the moment. But definitely good to keep in mind.

**Comment by hannahkane** [comment]
WFM.

Meta-comment about etherpads: I'm not sure that etherpad is a widely understood tool. Wondering if it would be useful to have a tooltip or something that explains what is it, why we use it, how to use it—something we could use throughout all Mofo properties. Feels like a teachable moment, but maybe I'm overthinking things. Definitely outside the scope of this issue. :)
