### ISSUE TITLE
Proposal: delay requesting the public_repo scope

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#18]
Currently we request the `public_repo` scope with GitHub authentication upon log in. This helps us encourage users to fork code -- remixing is an important skills for learning and building tools helping science on the web. We don't want to loose this functionality, especially since we'll be using this for our upcoming community blogging system.

Problem:
`public_scope` is an admittedly permissive scope, giving us write access to all repos the users has access to, including organization repos. We don't actually need or want this -- neither does some of our community: #11 

Proposal:
The best compromise I can think of now, is to request `no scope` upon log in. Then, when a user wants to take part in Collaborate, request `public_scope`. This would require rewriting some of our authentication code and we'd have less smooth user process around Collaborate. We'll also have to consider how we'll work with tiered scopes with the new blogging system - which will be built around forking.

My biggest concern with this approach is the fact that our future plans are tied around forking and encouraging more interaction with code.

**Comment by wking** [comment]
On Mon, Feb 23, 2015 at 08:59:30AM -0800, Abigail Cabunoc wrote:
> The best compromise I can think of now, is to request `no scope`
> upon log in. Then, when a user wants to take part in Collaborate,
> request `public_scope`.

The first time you want to fork a repo for someone, can you:

1. Check to see if that user has an existing fork of the repository in
   question.  If they do, there's no need to do anything else.


2. If they don't already have a fork, prompt with:

     We'd like to fork $REPO for you automatically.  Granting us the
     ‘public_scope’ permission will allow us to fork repositories on
     on your behalf going forward.  Alternatively, you can create any
     required forks manually.

     <grant permission>  <forked manually>  <cancel>

Then users who aren't comfortable with the broad permission can fork
by hand.

**Comment by acabunoc** [comment]
@wking - that sounds like a good workflow

**Comment by acabunoc** [comment]
from the old site, closing!
