### ISSUE TITLE
Headers are invisible

### ISSUE THREAD

**Issue by rgaiacs** [mozilla/science.mozilla.org#19]
![m](https://cloud.githubusercontent.com/assets/1506457/6401156/155bda88-bddd-11e4-8ee4-2197cd9aa4bf.jpg)

To check that the headers are invisible:

![m2](https://cloud.githubusercontent.com/assets/1506457/6401168/3f354d80-bddd-11e4-9682-34eb1a72190c.jpg)

**Comment by r-gaia-cs** [comment]
This happens on

- Firefox 27-Nightly
- Chromium 40
- Epiphany/Web 3.14.2

at a Linux machine.

**Comment by acabunoc** [comment]
From @wking:

https://bugzilla.mozilla.org/show_bug.cgi?id=1083437

Will implement fix

**Comment by acabunoc** [comment]
On Arch linux:
http://www.reddit.com/r/archlinux/comments/2gix0k/rust_website_now_with_invisible_fonts/

**Comment by r-gaia-cs** [comment]
@acabunoc, thanks. Install ttf-fira-sans and ttf-fira-mono solve the problem (but I didn't have ttf-google-fonts-git).

**Comment by wking** [comment]
On Wed, Mar 04, 2015 at 04:08:11PM -0800, Raniere Silva wrote:
> Install ttf-fira-sans and ttf-fira-mono solve the problem (but I
> didn't have ttf-google-fonts-git).

I think "install the fonts locally" misses the point ;).  The Arch
link [1] was saying (I think) that the ttf-google-fonts-git package
was broken, causing the browser to *think* the font was installed (or
working, or something), when in fact it wasn't.  The Firefox bug was
maybe a CORS issue [2], but I haven't read it in enough detail to
really understand what was happening.

Hitting [3] after clearing my cache and watching my network activity
shows:

  GET http://fonts.googleapis.com/css?family=Fira+Sans:300
    200

which includes:

  src: local('Fira Sans Light'), local('FiraSans-Light'),
	  url(http://fonts.gstatic.com/s/firasans/v5/VTBnrK42EiOBncVyQXZ7j3hCUOGz7vYGh680lGh-uXM.woff) format('woff');

Later in my network activity, I see:

  GET http://fonts.gstatic.com/s/firasans/v5/VTBnrK42EiOBncVyQXZ7j3hCUOGz7vYGh680lGh-uXM.woff
    200

So I have no Fira Sans or Google fonts locally, but my browser hits
the fallback URL and downloads the font.  I'm not sure why it's not
drawing with it though.

[1]: http://www.reddit.com/r/archlinux/comments/2gix0k/rust_website_now_with_invisible_fonts/
[2]: https://bugzilla.mozilla.org/show_bug.cgi?id=1083437#c10
[3]: http://www.mozillascience.org/blog

**Comment by acabunoc** [comment]
Thanks for reading through that, both! I wasn't sure if that's really the problem -- I know @r-gaia-cs is on Arch, @wking are you on Arch, too?

Such a strange problem, still researching :)

**Comment by wking** [comment]
On Wed, Mar 04, 2015 at 05:04:22PM -0800, Abigail Cabunoc wrote:
> Thanks for reading through that, both! I wasn't sure if that's
> really the problem -- I know @r-gaia-cs is on Arch, @wking are you
> on Arch, too?

I'm on Gentoo, but they're both locally-compiled, source-based
distributions (for the most part).

**Comment by hannahkane** [comment]
I think this is no longer relevant since we moved to science.mozilla.org, so closing.
