### ISSUE TITLE
Copy for fellowship pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#194]
I will updated copy for the fellowship pages (https://redpen.io/p/eb9d7534bcf4dfcc17). I've copied what is on the current site into the copy doc so please edit away https://docs.google.com/a/mozilla.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit?usp=sharing

One suggestion is to try and avoid having a FAQ page. FAQ pages generally have poor usability because the content has no hierarchy. If we think someone will wonder "I live outside of the US, UK or Canada - am I eligible?" then we should put that in the Eligibility Criteria section instead.

Not too sure how is best to take this on? @acabunoc @kaythaney @auremoser @zee-moz @stephwright cc @hannahkane

**Comment by hannahkane** [comment]
+1 to eliminating the FAQ and instead working those into the other tabs. Let me know if I can help by offering some suggestions for how to do that. (Happy to do that, though I'm likely not the best person since I don't know what program elements have changed since last year.)

**Comment by auremoser** [comment]
I'm going to gently push back on this, feel free to veto me. FAQs are kind of a catch all for lots of material that is ancillary to core-content but maybe will save us a few individual email. I know they lack hierarchy but I think people expect that something like this will exist, and are comfortable scrolling for clarity. I feel like having all of FAQ caveats in the base content will make the application docs verbose and insecure in tone (like, including a clarification about why we're sorry you can't apply from outside the US/UK and Canada (first question in the FAQ) right after we list the requirement that you be "Currently working at a research institution in the US, UK or Canada." seems a bit redundant. An FAQ captures those redundancies in a different location which makes us seem considerate but not milquetoast in our assertions. 

Perhaps we could just group the FAQ questions under themed headings similar to those in the core content (like "Eligibility Criteria" and "Stipends"...)? I'm happy to group them and eliminate those that are now obsolete. Also, maybe I'm not explaining myself well, and I'm sorry I didn't address this before, but if I had questions about content/necessary requests in the application docs, I'd probably look for an FAQ.

**Comment by kaythaney** [comment]
+1 to that. the info in the FAQ was also clearly laid out in the
requirements last year. didn't keep us from getting tons of folks asking
the same questions. :)

On Wed, Apr 20, 2016 at 1:25 PM, Aurelia Moser <notifications@github.com>
wrote:

> I'm going to gently push back on this, feel free to veto me. FAQs are kind
> of a catch all for lots of material that is ancillary to core-content but
> maybe will save us a few individual email. I know they lack hierarchy but I
> think people expect that something like this will exist, and are
> comfortable scrolling for clarity. I feel like having all of FAQ caveats in
> the base content will make the application docs verbose and insecure in
> tone (like, including a clarification about why we're sorry you can't apply
> from outside the US/UK and Canada (first question in the FAQ) right after
> we list the requirement that you be "Currently working at a research
> institution in the US, UK or Canada." seems a bit redundant. An FAQ
> captures those redundancies in a different location which makes us seem
> considerate but not milquetoast in our assertions.
>
> Perhaps we could just group the FAQ questions under themed headings
> similar to those in the core content (like "Eligibility Criteria" and
> "Stipends"...)? I'm happy to group them and eliminate those that are now
> obsolete. Also, maybe I'm not explaining myself well, and I'm sorry I
> didn't address this before, but if I had questions about content/necessary
> requests in the application docs, I'd probably look for an FAQ.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/issues/194#issuecomment-212523743>
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by kaythaney** [comment]
also, just to flag, we're looking at broadening the call for year 2 beyond
the US, UK and Canada, but are awaiting a meeting with ops/legal. that'll
take a few weeks. @auremoser and i are working on updates to the text in
the meantime.

don't let that hold you up - will be minor text tweaks. just flagging that
confirmation on that is likely a few weeks out.



On Wed, Apr 20, 2016 at 1:57 PM, Kaitlin Thaney <kaitlin.thaney@gmail.com>
wrote:

> +1 to that. the info in the FAQ was also clearly laid out in the
> requirements last year. didn't keep us from getting tons of folks asking
> the same questions. :)
>
> On Wed, Apr 20, 2016 at 1:25 PM, Aurelia Moser <notifications@github.com>
> wrote:
>
>> I'm going to gently push back on this, feel free to veto me. FAQs are
>> kind of a catch all for lots of material that is ancillary to core-content
>> but maybe will save us a few individual email. I know they lack hierarchy
>> but I think people expect that something like this will exist, and are
>> comfortable scrolling for clarity. I feel like having all of FAQ caveats in
>> the base content will make the application docs verbose and insecure in
>> tone (like, including a clarification about why we're sorry you can't apply
>> from outside the US/UK and Canada (first question in the FAQ) right after
>> we list the requirement that you be "Currently working at a research
>> institution in the US, UK or Canada." seems a bit redundant. An FAQ
>> captures those redundancies in a different location which makes us seem
>> considerate but not milquetoast in our assertions.
>>
>> Perhaps we could just group the FAQ questions under themed headings
>> similar to those in the core content (like "Eligibility Criteria" and
>> "Stipends"...)? I'm happy to group them and eliminate those that are now
>> obsolete. Also, maybe I'm not explaining myself well, and I'm sorry I
>> didn't address this before, but if I had questions about content/necessary
>> requests in the application docs, I'd probably look for an FAQ.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mozilla/science.mozilla.org/issues/194#issuecomment-212523743>
>>
>
>
>
> --
> @kaythaney <http://twitter.com/kaythaney/>
> @MozillaScience <http://twitter.com/mozillascience>
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by stephwright** [comment]
Another +1 from me for what Aure & KT said.

On Wed, Apr 20, 2016 at 10:57 AM, Kaitlin Thaney <notifications@github.com>
wrote:

> +1 to that. the info in the FAQ was also clearly laid out in the
> requirements last year. didn't keep us from getting tons of folks asking
> the same questions. :)
>
> On Wed, Apr 20, 2016 at 1:25 PM, Aurelia Moser <notifications@github.com>
> wrote:
>
> > I'm going to gently push back on this, feel free to veto me. FAQs are
> kind
> > of a catch all for lots of material that is ancillary to core-content but
> > maybe will save us a few individual email. I know they lack hierarchy
> but I
> > think people expect that something like this will exist, and are
> > comfortable scrolling for clarity. I feel like having all of FAQ caveats
> in
> > the base content will make the application docs verbose and insecure in
> > tone (like, including a clarification about why we're sorry you can't
> apply
> > from outside the US/UK and Canada (first question in the FAQ) right after
> > we list the requirement that you be "Currently working at a research
> > institution in the US, UK or Canada." seems a bit redundant. An FAQ
> > captures those redundancies in a different location which makes us seem
> > considerate but not milquetoast in our assertions.
> >
> > Perhaps we could just group the FAQ questions under themed headings
> > similar to those in the core content (like "Eligibility Criteria" and
> > "Stipends"...)? I'm happy to group them and eliminate those that are now
> > obsolete. Also, maybe I'm not explaining myself well, and I'm sorry I
> > didn't address this before, but if I had questions about
> content/necessary
> > requests in the application docs, I'd probably look for an FAQ.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mozilla/science.mozilla.org/issues/194#issuecomment-212523743
> >
> >
>
>
>
> --
> @kaythaney <http://twitter.com/kaythaney/>
> @MozillaScience <http://twitter.com/mozillascience>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/issues/194#issuecomment-212535826>
>



-- 
Stephanie Wright
--------------------------------------------------------------------------------------
Open Data Training Lead, Mozilla Science Lab
Twitter @shefw  | GitHub @stephwright | Skype: stephanie_4504
ORCID: 0000-0003-3829-318X
"The opposite of 'open' isn't 'closed'.  The opposite of 'open' is
'broken'." ~ John Wilbanks

**Comment by kristinashu** [comment]
Sounds good, thanks everyone for weighing in. I'll add an FAQ tab to the mocks.

**Comment by auremoser** [comment]
thank you @kristinashu !

**Comment by hannahkane** [comment]
Are we good on this ticket, or do we need to finalize more copy?

**Comment by kristinashu** [comment]
Do we know the deadline date for applications?

**Comment by kaythaney** [comment]
Let's say July 15. :) (cc @auremoser)

sent on the move. apologies for typos.

**Comment by kristinashu** [comment]
Thanks! Closing this ticket.
