### ISSUE TITLE
(Current site) Update https://mozillascience.org/fellows and promote on homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#208]
I believe we want to promote the Fellowships program before the Global Sprint (June 2). 

Can use same copy that's [being finalized](https://github.com/mozilla/science.mozilla.org/issues/194) for the non-contingency plan, but use a non-tabbed structure, as on the current production site.

Will need design support for promoting on the current site's homepage. 

Might also want to temporarily add a Fellowships item to the top-level nav (as the last item?)

@acabunoc @kristinashu - does this all seem right to you?

**Comment by kristinashu** [comment]
Those updates sound right. I think Fellowship applications open at the end of May?

**Comment by kristinashu** [comment]
This was part of the contingency plan which we didn't end up using!
