### ISSUE TITLE
(Current site) Update Collaborate

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#212]
- [ ] update section name from Collaborate to Projects
 - [ ] update url + add a redirect
 - [ ] update all the intro copy to the new copy - https://redpen.io/jc2e62ed8f6f3f6ef5
 - [ ] remove the about page which is out of date https://www.mozillascience.org/collaborate/about

**Comment by kristinashu** [comment]
This was part of the contingency plan which we didn't end up using!
