### ISSUE TITLE
(Current site) Add Resources page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#219]
- [ ] Perhaps just a list, grouped by category - title (linked) + description from https://docs.google.com/spreadsheets/d/1aQhmnDO4zYt24sD8ItYeesbAn2TUiHzKyllSkzs4VN0/edit#gid=0
 - [ ] Needs a bit of intro text
 - [ ] Add to top level nav

Thinking we don't need tags or "Add a resource" functionality

**Comment by kristinashu** [comment]
This was part of the contingency plan which we didn't end up using!
