### ISSUE TITLE
RSS feed working?

### ISSUE THREAD

**Issue by BillMills** [mozilla/science.mozilla.org#22]
It's unclear if the blog's RSS feed is working. Svetlana added it to the open science planet (http://science.okfn.org/blog/), but I'm not seeing any MSL posts popping up there, and things are working on her end for other people, soooo....

**Comment by mixtrak** [comment]
The [supplied feed URL](mozillascience.org/feed) doesn't return any results through Feedly. However, I was able to subscribe via searching for "Mozilla Science". But I don't really understand how Feedly or RSS works in detail (๑′°︿°๑)

Then I tried Outlook 2013 desktop... couldn't get mozillascience.org/feed to work, but http://mozillascience.org/feed did. I then plugged that URL into Feedly and it returned a result this time.

Maybe the http:// is required in some contexts.

**Comment by BillMills** [comment]
ping @belkinsa - any chance this is what's up over at the planet?

**Comment by belkinsa** [comment]
On 03/25/2015 12:40 AM, Bill Mills wrote:
> ping @belkinsa <https://github.com/belkinsa> - any chance this is what's
> up over at the planet?

I was told by a system admin that the feed broke the cron job and I had 
to remove it.  But if you are certain that it is working again, I can 
re-add and check if it works.
-- 
Svetlana Belkin
A.K.A: belkinsa
User Wiki page: https://wiki.ubuntu.com/belkinsa

**Comment by BillMills** [comment]
We just got added to the [mozilla planet](http://planet.mozilla.org/) and our posts are appearing there, so I think we're okay.

**Comment by belkinsa** [comment]
What was the address that you used?

**Comment by mixtrak** [comment]
Who, me?

Http://mozillascience.(org or com? I forget)/feed

Sent from mobile
________________________________

**Comment by belkinsa** [comment]
Doesn't work, and that was too @BillMills or @acabunoc

**Comment by acabunoc** [comment]
Thanks for all the details @belkinsa & @mixtrak! I tested the feed in a few popular feed readers, but I'm sure I missed some cases.

Feed to use:
http://www.mozillascience.org/feed

I haven't been having problems in feedly or other rss readers -- @mixtrak, could you expand on 'doesn't return any results through Feedly'?
http://feedly.com/i/subscription/feed/http://mozillascience.org/feed/

@belkinsa - do you have any more details to help me understand what isn't working? Could you send the cron job?

**Comment by wking** [comment]
On Mon, Mar 30, 2015 at 12:54:01PM -0700, Abigail Cabunoc wrote:
> I tested the feed in a few popular feed readers, but I'm sure I
> missed some cases.
> 
> Feed to use:
> http://www.mozillascience.org/feed

The W3C hosts a feed validator [1].  It complains about a few issues
[2], and each complaint links to some help explaining what they think
you should be doing.

Cheers,
Trevor

[1]: http://validator.w3.org/feed/
[2]: http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.mozillascience.org%2Ffeed

**Comment by acabunoc** [comment]
Thanks @wking! Super helpful

**Comment by belkinsa** [comment]
@acabunoc and @BillMills I added the feed back in and if it doesn't work I will ask the system admin for the cron job error output.

**Comment by mixtrak** [comment]
Sure, I can give more details. On the Feedly website there's a search box to find more RSS content to add to your dash. You can either use search terms, or just input the URL of the feed to add it directly. When I search for the words "Mozilla Science", it finds the blog, and I can add it no worries. But the URL "mozillescience.org/feed" doesn't return any results. On the other hand, the URL "http://mozillascience.org/feed" does indeed find your blog. That http:// at the front is crucial in this instance (and also, it turns out, when using Outlook's RSS functionality), but I have no idea whether this is related to your other problems. @Belkinsa has evidence that it's not.

Sent from mobile
________________________________

**Comment by acabunoc** [comment]
Hey all,

Made a few changes to the feed based on the validator -- let me know if this works for you @belkinsa!

6aa434a3fd34e0df25a12977e05e7408a03ebeab

**Comment by acabunoc** [comment]
ping @belkinsa -- any news if this made a difference at all?

**Comment by belkinsa** [comment]
No difference. I see nothing on the FeedPress interface and no word of a fail from the system admin.

**Comment by acabunoc** [comment]
So strange! Thanks for the update

**Comment by belkinsa** [comment]
Not a problem, I might still check with the system admin if there was a failure.

**Comment by acabunoc** [comment]
from the old site! closing, but i've opened a new RSS issue for the new site
