### ISSUE TITLE
(Current site) Add Study Groups page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#220]
Study Groups page (thinking this would be all of the content on [this page](https://redpen.io/ow3163da6caa22acde) and [this page](https://redpen.io/de9fb9639192c1b4e9), but in a non-tabbed structure, and perhaps without the map) + add top level nav item for SGs

**Comment by acabunoc** [comment]
This can replace the /training page

**Comment by kristinashu** [comment]
This was part of the contingency plan which we didn't end up using!
