### ISSUE TITLE
[design QA] Homepage - What's New styling

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#233]
Minor styling tweaks:
- "What's New" text bigger - maybe 2.65rem instead of 1.74
- "Resource", "Project", "Blog" titles grey instead of green and 300 instead of 400
- "Code Review in the Lab" titles 200 instead of 100
- titles are links so should have hover state

Might be tricky, but can the three box heights be the same?

Comp:
<img width="1234" alt="screen shot 2016-05-10 at 10 31 03 am" src="https://cloud.githubusercontent.com/assets/1068783/15156123/657fab2c-169a-11e6-92d1-68c905f8ef8e.png">

Staging:
<img width="1237" alt="screen shot 2016-05-10 at 10 31 17 am" src="https://cloud.githubusercontent.com/assets/1068783/15156124/657fec7c-169a-11e6-8a0d-a7f362607183.png">

**Comment by alanmoo** [comment]
It seems like most of the concerns here stem from identifying typographic styles. Is there a set of font sizes/weights used across the project so that we can use a few classes instead of manually setting everything?

**Comment by kristinashu** [comment]
Links and box height are fixed. I think we can close this ticket and move the font styling to https://github.com/mozilla/science.mozilla.org/issues/228 and https://github.com/mozilla/science.mozilla.org/issues/405
