### ISSUE TITLE
[Design QA] Newsletter sign up - add error message if box is unchecked

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#235]
If someone clicks subscribe but does not check the "I'm okay with Mozilla handling my info as explained in this Privacy Notice" box then they should get an error message saying to check it.

**Comment by gvn** [comment]
Is there design for this?

**Comment by kristinashu** [comment]
Nothing mocked up, just a combo of what you have for the email address error and what's on encrypt campaign:
<img width="343" alt="screen shot 2016-05-02 at 12 02 46 pm" src="https://cloud.githubusercontent.com/assets/1068783/14964632/ef2d286a-105d-11e6-8241-29d9a01126d9.png">
