### ISSUE TITLE
[design QA] Newsletter confirmation

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#236]
After successfully subscribing to the newsletter we get redirected to this awful screen:
![screen shot 2016-04-21 at 11 09 22 am](https://cloud.githubusercontent.com/assets/1068783/14724480/491898be-07cb-11e6-9a1e-2740e4b1cb53.png)

Is there a way around his? It would be ideal if the user did not have to leave the science site. This doesn't seem to happen on http://advocacy.mozilla.org/encrypt/

**Comment by gvn** [comment]
I'm going to go with *probably not.* Looks like the encryption site uses a totally different email system. I'm pretty sure that to get rid of it we'd have to migrate Mozillascience to a different system, which is probably not trivial.

However, I'm not absolutely certain. Maybe we can get someone from the Science team to weigh in.

**Comment by kristinashu** [comment]
Based on our stand today, our goal for now is to open this confirmation in a new tab.

I'll open another ticket to explore migrating to Exact Target so that confirmation can happen within the science site and so we're using the service moco and mofo are moving towards.

**Comment by gvn** [comment]
Sounds good!
