### ISSUE TITLE
Github pop-up respawns in an infinite loop when I try to sign up for a forum account

### ISSUE THREAD

**Issue by jpellman** [mozilla/science.mozilla.org#24]
Hi MozScience,

As you might have guessed from the issue title, I ran into a strange error when trying to sign up for an account on the forum.  Basically, the window requesting authorization from Github re-spawned in an endless loop, making it impossible for me to fill out the user info form (username, real name, etc)  About my configuration:

-Mac OS X 10.10
-Firefox 36.0.1 (Ghostery installed)
-Already logged into Github

I switched to Safari temporarily (where I wasn't logged into Github), and was able to sign up there.  Let me know if there are any things you'd like me to try or if you need any other details about my setup that could potentially be causing the problem.

**Comment by acabunoc** [comment]
Thanks for the feedback @jpellman! I'm glad you were able to log in -- do you still have this problem now that you have an account?

I'll keep looking into this for you

**Comment by jpellman** [comment]
I haven't encountered the problem since signing up successfully in Safari.  I'm able to log in with Firefox without any issues- it was just during account creation when I encountered this.

**Comment by acabunoc** [comment]
this is from the old site, closing!
