### ISSUE TITLE
[design QA] background images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#240]
Looks good in FF but in Chrome and Safari the Events/Study Group background and the What's New background aren't filling the browser 

staging:
<img width="1301" alt="screen shot 2016-04-21 at 2 51 56 pm" src="https://cloud.githubusercontent.com/assets/1068783/14725437/c7d14df4-07d0-11e6-8bd9-fcfb46abfb53.png">

**Comment by kristinashu** [comment]
Actually, it's cut off in FF too. Images and color background should fill the browser window. While text content can have max width, as is now.

**Comment by alanmoo** [comment]
The issue with images filling the background usually has to do with width and scaling; There has to be a upper limit of the image at some browser width. On smaller screens we can make it fill to the max-width of the image, but at larger screen sizes what would you like it to do?

**Comment by kristinashu** [comment]
Can it be like the background images on https://advocacy.mozilla.org/open-web-fellows/ ? I like how the height stays the same and the width fills the full browser. Maybe it has a max width but it must be pretty wide?

**Comment by hannahkane** [comment]
Adding this to May 20 because I think it looks like a bug, but not a blocker for launch.
