### ISSUE TITLE
Prep design files for devs

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#248]

**Comment by kristinashu** [comment]
I've added icons for event and fellowship pages to the assets folder: https://drive.google.com/open?id=0B2irLVDJivhLUm1HZExlOUVkcFk

Here is the latest .ia file: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLMGRYeEF0LTZ5QWc/view?usp=sharing

cc @gvn @alanmoo

**Comment by gvn** [comment]
Thanks!
