### ISSUE TITLE
Make it easy for contributors to contribute! 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#251]
Once dev has settled down we should make sure it's easy for contributors to get involoved: create tickets with lots of detail and possibly add a label to them.

I think @taml and @mmhyamin are both interested in contributing to this repo!

**Comment by taml** [comment]
@kristinashu I'm definitely interested!

**Comment by hannahkane** [comment]
We should also create a CONTRIBUTING.md file. @acabunoc @alanmoo - is that something either of you would be able to work on?

**Comment by alanmoo** [comment]
Yeah; A lot of info is in our [MoFo standards](https://GitHub.com/mozillafoundation/mofo-standards). What other type of information is useful?

**Comment by hannahkane** [comment]
The CONTRIBUTING file could point to Mofo standards, but could also have some info specific to this repo. e.g. "Look for issues with 'good first bug' label"

Also...we should probably do a triage of this repo soon and identify some good first bugs. Will schedule.

**Comment by acabunoc** [comment]
contributing guidelines template! https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md
