### ISSUE TITLE
Data needed from Events API

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#274]
Looking at https://redpen.io/aq0c17cb0774ab55bd and https://redpen.io/vxab11f78998c91e29, there seems to be a bunch of odds and ends of data that are needed from the events API. I may be able to calculate some of these on the front end, but I'm not quite sure where to draw that line. Maybe @acabunoc can help?

* "tag" format of the date (single date or multiple dates)- can possibly be calculated
* "time" (next to location)- should I do some logic about the duration? Greater than 4 hours becomes an entire day maybe?
* Button/link details- Label and a way to indicate its target (some seem to be links to the event, some seem to be external links)
* Short description vs detail description? Or is this the intent of `additional_notes`?
* Formatting of longer description data (additional notes?) - will this eventually support markdown or something? 
* According to the comps, the button link for the summary can be different than what's inside. Maybe this shouldn't happen? ("Call Details" vs. "Etherpad Link") https://redpen.io/vxab11f78998c91e29?showing_comment=1771381 and https://redpen.io/aq0c17cb0774ab55bd?showing_comment=1771382

**Comment by acabunoc** [comment]
One other thing you will need to consider is the time zone. 

For events happening in a certain location (Like a [Berlin Community Meetup](https://mozillascience.org/working-open-workshop-mixer-february-4th)), that should be displayed in the local time w/ appropriate timezone.

For worldwide events (like our calls), that should be displayed in the viewers' timezone.

---

For your other notes:


>"tag" format of the date (single date or multiple dates)- can possibly be calculated

yes, if it spans multiple dates / is > 24h, show multiple dates

>"time" (next to location)- should I do some logic about the duration? Greater than 4 hours becomes an entire day maybe?

I would show the time if you're displaying a single date. Calculated above ^

>Button/link details- Label and a way to indicate its target (some seem to be links to the event, some seem to be external links)

On the summary page? I think those should all be links to the event details page

>Short description vs detail description? Or is this the intent of additional_notes?

additional_notes is the etherpad. I don't think we currently have a short description in the api

>Formatting of longer description data (additional notes?) - will this eventually support markdown or something?

maybe for phase 2?

>According to the comps, the button link for the summary can be different than what's inside. Maybe this shouldn't happen? ("Call Details" vs. "Etherpad Link") https://redpen.io/vxab11f78998c91e29?showing_comment=1771381 and https://redpen.io/aq0c17cb0774ab55bd?showing_comment=1771382

I think it's okay that they are different:
Summary link -> goes to [details page](https://redpen.io/vxab11f78998c91e29) for the event
Etherpad link -> goes to etherpad for the event (if it's a call that has an etherpad -- `additional_notes`)

**Comment by acabunoc** [comment]
@alanmoo I feel like looking at the existing data would help here -- let me know if you want access to our current mongodb while you wait for the migration!

**Comment by alanmoo** [comment]
Thanks @acabunoc, this was really helpful.

`additional_notes` is a link to the etherpad?

**Comment by acabunoc** [comment]
@alanmoo 
> additional_notes is a link to the etherpad?

yes!

**Comment by alanmoo** [comment]
Ok, I'm going to close this and implement using this ticket for guidance.
