### ISSUE TITLE
Refactor tab switcher for mobile

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#283]
Add icon-ification of tabs for narrow viewports.

**Comment by gvn** [comment]
@kristinashu Are there tab icons for the Study Groups and Events tab switchers?

**Comment by kristinashu** [comment]
All of them should now be in the assets folder https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLUm1HZExlOUVkcFk&usp=sharing

and attached here
[tab icons.zip](https://github.com/mozilla/science.mozilla.org/files/262005/tab.icons.zip)
