### ISSUE TITLE
API driven vs templated event pages

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#291]
It seems like some of the events (global sprint, hack day at least) have a bit more styling/data than would make sense to fit into the API. I can pull strings from the API and render them as HTML, but that doesn't seem like it's going to do everything that's desired of those event pages. Should some of them be hard-coded as HTML pages in the repo?

@acabunoc @gideonthomas @alicoding @kristinashu @gvn

**Comment by kristinashu** [comment]
Is this the Hack Day you're talking about? https://www.mozillascience.org/space-apps-2016 Seems like it's actually a blog post. Can the content be duplicated as an event? Then it should be straight forward content - text and two images (no comments). 

Global Sprint seems very custom though https://www.mozillascience.org/global-sprint-2016

**Comment by alanmoo** [comment]
That's the one

**Comment by gideonthomas** [comment]
Oh, hmm yeah so for that, that content wasn't stored in the db so I copied the page source from the page linked above and used that as the description in the db. Let me know what that needs to be changed to.

**Comment by acabunoc** [comment]
Yeah, on the current site I wrote a [custom template](https://github.com/mozilla/science.mozilla.org/blob/mozillascience.org/views/events/globalsprint2016.jade) for the global sprint.

I've been assuming that events will be less boutique going forward -- if it's easier to get rid of some of the custom elements, I'm fine with that! As long as the events are still usable / contain the same info, I'm happy.

@alanmoo - I'm happy to let you decide which direction we should go in for these pages

**Comment by alanmoo** [comment]
I think the events/project pages need a reevaluation of the data sets in general- short descriptions specifically come to mind. I'll take a look at the events/projects (and related individual pages) and generate a list of fields I'd expect, based on the comps.

**Comment by acabunoc** [comment]
I'm happy to manually go through and curate the data we have on our existing events/projects to get them in a format that works well for you! Thanks for bringing this up / evaluating :)

**Comment by alanmoo** [comment]
It seems like the main thing that's needed right now is short descriptions for projects and events. @acabunoc if you can massage the data for that, it should solve a good amount of the issues, especially coupled with the newly resolved #292 and #294

**Comment by acabunoc** [comment]
Sounds good, I just need @gideonthomas to add a short_description field to events

**Comment by gideonthomas** [comment]
ah @acabunoc will do now

**Comment by gideonthomas** [comment]
@acabunoc done :)

**Comment by acabunoc** [comment]
I added images & short_description for each project (& deleted some projects we didn't need)

I think I'm going to have to modify the long description for several of the events once there's an event details page up.

**Comment by alanmoo** [comment]
Do the short descriptions have HTML in them? Or can I just embed them as text nodes?

**Comment by acabunoc** [comment]
just text! there will probably be html in the long description, though

**Comment by gideonthomas** [comment]
@acabunoc does anything else need to be done here?
