### ISSUE TITLE
Update logo so it will work as an svg

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#293]

**Comment by kristinashu** [comment]
I've updated the logo so it no longer has any overlay effects and should now work as an SVG:
[logo-mozillascience.svg.zip](https://github.com/mozilla/science.mozilla.org/files/251004/logo-mozillascience.svg.zip)

<img width="792" alt="screen shot 2016-05-05 at 1 17 10 pm" src="https://cloud.githubusercontent.com/assets/1068783/15055865/b97c0ac0-12c3-11e6-8598-522d2e4a4c6b.png">

**Comment by kristinashu** [comment]
@gvn @alanmoo guess you can update the logo when you get the chance 

cc @acabunoc

**Comment by gvn** [comment]
![f9623bec7b5c45196af9d727ba2d874dd86c58ec](https://cloud.githubusercontent.com/assets/206379/15057958/670e8dc0-12ce-11e6-91f4-ce48798fb00d.gif)
