### ISSUE TITLE
Finalize copy for study groups

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#296]
Based on design in https://github.com/mozilla/science.mozilla.org/issues/127

We need copy for https://redpen.io/ow3163da6caa22acde and https://redpen.io/de9fb9639192c1b4e9

Copy doc: https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit

**Comment by acabunoc** [comment]
I think @auremoser would be the best person for this

**Comment by hannahkane** [comment]
Moving to May 20 to wrap

**Comment by auremoser** [comment]
I added some copy for this, let me know if it's too much or not enough. Apologies for the delay!

**Comment by hannahkane** [comment]
Thanks, @auremoser! I'm closing this, but tagging @alanmoo who's building the pages.

**Comment by alanmoo** [comment]
I literally just finished copying this stuff into the site. Thanks!

**Comment by hannahkane** [comment]
@alanmoo you are so ahead of the game.

**Comment by auremoser** [comment]
Superdupe thanks @alanmoo + @hannahkane

On Fri, May 13, 2016 at 12:40 PM, Alan Mooiman <notifications@github.com>
wrote:

> I literally just finished copying this stuff into the site. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/issues/296#issuecomment-219095887>
>



-- 
Aurelia Moser
Community Lead, Mozilla Science Lab
Twitter @auremoser | GitHub @auremoser | Skype: auremoser1
