### ISSUE TITLE
Modify format of user response in events

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#297]
Example route: https://api-mozillascience-staging.herokuapp.com/events/1/?expand=projects,users

I appreciate the "leads" array inside each project, but can you name that "users" and give the users the "role" key so that I can reuse a react component? (The component is built using https://api-mozillascience-staging.herokuapp.com/projects/?expand=users)

@gideonthomas @alicoding

**Comment by gideonthomas** [comment]
I don't follow, the component is built using `/projects?expand=users` but you need the change in `/events/<id>?expand=projects,users`?

**Comment by alanmoo** [comment]
Yeah, I need the structure of the user objects from the latter to match the former.

**Comment by gideonthomas** [comment]
let's chat about this on a call
