### ISSUE TITLE
Update select and search input styling upstream

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#303]

**Comment by alanmoo** [comment]
Dear future @gvn,

I've found a solution for this that doesn't require updating Bootstrap right now, but while exploring I realized that there will need to be updates to [three-up's styles](https://github.com/mozilla/science.mozilla.org/blob/master/app/react/components/three-up/three-up.scss). `make-col` and `make-col-span` become one mixin.

**Comment by gvn** [comment]
Ok, cool. Do you want to throw a ticket in the backlog (Blue Sky, I guess) for that update?
