### ISSUE TITLE
Consolidate project tags

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/science.mozilla.org#305]
There are over 100 tags in the db and most of them are redundant and/or repetitive. They need to be manually consolidated into a smaller amount of tags that we want and are relevant to projects. This "manual" operation will be done through the Django admin interface.

**Comment by acabunoc** [comment]
tags consolidated! Still 76, but they make sense now!

**Comment by gideonthomas** [comment]
wooo thanks @acabunoc!
