### ISSUE TITLE
Create resources page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#309]
Jumbotron, lists of DataCard components, and filter.

API requirements:
* (paginated) array of resources, filterable by category. Each resource needs
  * Title
  * Short description
  * Categories

**Comment by kristinashu** [comment]
Content is here https://docs.google.com/spreadsheets/d/1aQhmnDO4zYt24sD8ItYeesbAn2TUiHzKyllSkzs4VN0/edit#gid=1510918447

**Comment by gvn** [comment]
Service: https://api-mozillascience-staging.herokuapp.com/resources/

**Comment by gvn** [comment]
Going to add the filtration in a follow-up ticket: https://github.com/mozilla/science.mozilla.org/issues/366
