### ISSUE TITLE
Build "Join a Study Group" tab

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#314]
https://redpen.io/ow3163da6caa22acde

- [ ] Needs intro content
- [ ] Might need help from @auremoser for quicker built out of map
- [ ] Need content from API

**Comment by kristinashu** [comment]
Copy will be here https://github.com/mozilla/science.mozilla.org/issues/296

I was thinking the map could just be a PNG for now. Image is in the assets folder https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLbE5SN2czTThLdEk&usp=sharing

List of all the locations and their links are in the copy doc https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit and I got the list from here http://mozillascience.github.io/studyGroupHandbook/ but the categories (like continent and countries) are new.

**Comment by auremoser** [comment]
Surely, I could put together a map but the static one works just as well for now, you can even do country-level captions like what we do on the [GDI site](https://www.girldevelopit.com/chapters/), or what Abby did for the [Global Sprint](https://mozillascience.org/global-sprint-2016).

Happy to help with a map, what we had before for the [Study Group Handbook Map](https://mozillascience.github.io/studyGroupHandbook/#map) was just geojson auto-magically rendered in ghub, but we did a cartodb map for the Global Sprint page, happy to make another one for SG and then just iframe in for the website. Let me know whatever's clever.
