### ISSUE TITLE
Build "Run a Study Group" tab

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#315]
https://redpen.io/de9fb9639192c1b4e9

Needs:

- [x] Content (description paragraphs)
- [x] Figure out where form submission goes
- [x] Data for study group cards

**Comment by kristinashu** [comment]
Content will be here but still waiting https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit

Submission should go to the same place as on the current site. Click "Start a Mozilla Study Group" and then "Submit" https://www.mozillascience.org/training 

Data is being finalized in https://github.com/mozilla/science.mozilla.org/issues/269#issuecomment-217565003 and can be found in the third tab "New Broader Categories" https://docs.google.com/a/mozilla.com/spreadsheets/d/1aQhmnDO4zYt24sD8ItYeesbAn2TUiHzKyllSkzs4VN0/edit?usp=sharing

**Comment by acabunoc** [comment]
Form on current site:
https://github.com/mozilla/science.mozilla.org/blob/mozillascience.org/views/training.jade#L62

**Comment by alanmoo** [comment]
Closed by #372
