### ISSUE TITLE
Add study group data and resource data

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/science.mozilla.org#317]
Adding actual data to the db

**Comment by acabunoc** [comment]
Study group data is in: https://api-mozillascience-staging.herokuapp.com/admin/study_groups/studygroup/

**Comment by acabunoc** [comment]
Resources data is in: https://api-mozillascience-staging.herokuapp.com/resources/

**Comment by acabunoc** [comment]
@auremoser & @zee-moz have access to edit / clean up the resources & study groups! Data is in, though :)
