### ISSUE TITLE
Thumbnail scaling

### ISSUE THREAD

**Issue by BillMills** [mozilla/science.mozilla.org#32]
Many of the thumbnails for Collaborate project stubs get cropped in weird places; suggest fixing thumbnail width and scaling height proportionally, with no crop.

**Comment by acabunoc** [comment]
But then they'd all have different heights...

**Comment by BillMills** [comment]
sure, but right now there's a bunch of text and logos just cut in half; there's room vertically for a bit of flex, no?

**Comment by riordan** [comment]
There's now the possibility of using [smartcrop.js](https://github.com/jwagner/smartcrop.js/), which is content-aware cropping that's tuned for areas "interestingess" of an image.

**Comment by BillMills** [comment]
Cool! And check out that [algorithm overview](https://github.com/jwagner/smartcrop.js/#algorithm-overview), I love it!

**Comment by acabunoc** [comment]
+1, thanks @riordan & @BillMills!
