### ISSUE TITLE
[design QA] Homepage - What's New content and links

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#334]
Before launch we need to updated the content to show the latest Project, Blog Post and Resource the science team want to feature.

Each one should link to it's detail page.

Science team might want to write the copy so that it doesn't truncate - copy should be about 250 characters and titles should be kept short.

**Comment by gvn** [comment]
@hannahkane Front end is blocked until we ascertain the feature choices and get copy.

**Comment by hannahkane** [comment]
@auremoser @zee-moz @stephwright @kaythaney please see above

**Comment by auremoser** [comment]
Happy to help, @kristinashu can you point to the part of the copy doc where you need this material?

**Comment by alanmoo** [comment]
@auremoser I just added a comment https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#heading=h.ppc8bywn72bz

**Comment by alanmoo** [comment]
This is for the three white boxes on the plant background. https://science-mozilla-org-staging.herokuapp.com/

**Comment by auremoser** [comment]
[Updated](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#), feel free to edit down to fit @alanmoo , as long as there are verbs and nouns in agreeable places.
