### ISSUE TITLE
[design QA] button styling

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#336]
I've mentioned this in a few styling tickets but it might warrant it's own ticket. 

Button text and line color should be "mobile blue" or white (when on a photo or color background).

All buttons should have the same font size, weight and have the same amount of padding.

Button hover state should fade to the inverse color like on https://mozilla-foundation-research.herokuapp.com/globalweb/ and https://advocacy.mozilla.org/

**Comment by kristinashu** [comment]
Some buttons like on Project detail page match the background color, which is good:
<img width="186" alt="screen shot 2016-05-11 at 10 46 52 am" src="https://cloud.githubusercontent.com/assets/1068783/15190627/c9c11dfc-1765-11e6-85d6-f8eafa4483d4.png">

But some, like the Blog load more button, are white when they should be the same color as the background:
<img width="155" alt="screen shot 2016-05-11 at 10 47 03 am" src="https://cloud.githubusercontent.com/assets/1068783/15190628/c9c1b000-1765-11e6-8d82-f5081cec9d79.png">

They should both look the same.

**Comment by alanmoo** [comment]
Fading to the inverse color is surprisingly near impossible to componentize at this point in web tech- We'd have to manually define the color of the text for each button based on what background it's over. I'd like to avoid having to specifically set the color for the hover state of each button, so could we settle on a hovered button text color to use across buttons? The background can still be transparent in normal state, it's just not possible to make the colored background have knocked out text.

(The one exception to this is white text/bordered buttons. There's a tricky way to use masks to our advantage then.)

**Comment by kristinashu** [comment]
I think the only two button options are:
- Any button on a light background would have a blue text and outline then go to solid blue with white text (even if the background is light grey) on hover. 
- Any button on a color or photo background would have white text and outline then go to solid white on hover. Sounds like you can do unique colored text for these but if not then maybe grey text would work instead. 
Does that sound right/possible?

**Comment by alanmoo** [comment]
Yes, this I can do.

**Comment by kristinashu** [comment]
Another thing, on the Event page, it looks like the buttons are slightly darker for buttons I have clicked on than buttons I have not. We don't need to distinguish so can they please all be the same blue. This might be the case on other pages but it's easier to see on Events since there are so many buttons.

**Comment by auremoser** [comment]
Adding to this issue, perhaps it's still under edits, but the button link on Event pages is no longer a button, it's now an offset link. This is fine, functionally, but looks a bit awkward and if the button is no longer going to have style, maybe we should just make it a regular link so the indent isn't strange vis-à-vis other text.
See [example here](https://science.mozilla.org/programs/events/community-call-feb-09-11-et).
Screenshot here:
![screen shot 2016-12-20 at 1 32 52 pm](https://cloud.githubusercontent.com/assets/1559703/21362632/3a9bf604-c6b7-11e6-8a14-8d25a0578163.png)

**Comment by alanmoo** [comment]
Looks like this was a casualty of an update to MoFo-Bootstrap. The `btn` class alone doesn't apply a background/outline, we need to apply a `btn-primary` or `btn-outline-primary` class in the markup saved in the database. Or a fix for event pages that automatically applies the appropriate style to `btn`s in the events view.

**Comment by akshatnitd** [comment]
May I be assigned to this issue?

**Comment by alanmoo** [comment]
Sure!

To clear up what needs to be done:
- [ ] Remove `background: transparent` from `#project-details .visit-repo`
- [ ] Find a way to target buttons on the event pages and either remove padding or make them look like buttons again.

Once those two things are done I think we should close this ticket and open a new one if there are any further issues, but those items should go a long way in making the site consistent.

**Comment by alanmoo** [comment]
(Unfortunately I can't assign to people outside the Mozilla org, but go ahead and work on it using the above guidance.)

**Comment by akshatnitd** [comment]
@alanmoo Okay. Working on it :+1:

**Comment by akshatnitd** [comment]
@alanmoo Can you please explain the second point?

**Comment by alanmoo** [comment]
Write some CSS that will *only* affect buttons on the event details pages (namely the "Etherpad Link" button on pages like https://science.mozilla.org/programs/events/studygroup-call-march-03) so that they either
a.) actually look like buttons (for example, the `.btn.btn-outline-info` style in use on pages like [this one](https://science.mozilla.org/projects/phyloviz)). 
b.) remove the styling (primarily the `padding`) from them so they just look like links.

**Comment by akshatnitd** [comment]
![deepinscreenshot20170218000809](https://cloud.githubusercontent.com/assets/12656846/23078349/62ad8b40-f56e-11e6-9dfc-6edd8e8a91e7.png)

Do I need to do it this way?

**Comment by auremoser** [comment]
Yes, that looks right, thank you @akshatnitd !

**Comment by akshatnitd** [comment]
Should I go ahead and send the PR?

**Comment by akshatnitd** [comment]
This is a preview of the 'View Repo' button.

![deepinscreenshot20170218001808](https://cloud.githubusercontent.com/assets/12656846/23078725/d5018790-f56f-11e6-9c3a-ecbc8cd71729.png)

**Comment by alanmoo** [comment]
Almost, the buttons should be transparent background normally, and white text/colored background on hover. You shouldn't have to write any code to get the "visit repo" button to look like this, you should be able to remove a line and have it work.

**Comment by akshatnitd** [comment]
@alanmoo I have made the on hover color, but the background is white, as it is defined in the btn class.

**Comment by alanmoo** [comment]
Open up a PR so I can take a look

**Comment by akshatnitd** [comment]
@alanmoo Just now saw that, in the mofo-bootstrap.css file, the btn classes have been overridden , and the background has been set to white in it. On removing it, it works fine.
