### ISSUE TITLE
[design QA] When navigating to a new page, should be scrolled to top

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#337]
Clicking on an internal page link doesn't bring user to the top of the new page. 

STR:
Go to Project or Event landing page https://science-mozilla-org-staging.herokuapp.com/projects
Scroll down and click on a project
When you get to the project detail page, you can not see the main nav bar because you are slightly scrolled down on the page. 

Learning had similar issue https://github.com/mozilla/learning.mozilla.org/issues/1812

**Comment by kristinashu** [comment]
Seems much worst in FF on my iPhone (I'm way more scrolled down the page).

**Comment by alanmoo** [comment]
@gvn as I suspected (and the learning ticket all but confirms), this is react-router related. We could band-aid this with changes to all the `<Link>` elements, but I'm starting to really feel like we should move to back-end use of react-router and reduce what gets sent to the user- this is really a content-driven site, after all, not a full webapp.

**Comment by gvn** [comment]
I don't think we should move to server-side react router until V2.

If there is a way we can do an interim fix, we should. This is really awkward on mobile, for example: tapping the "content mine" link on the homepage. We might just have to force the scroll to 0 on view changes.
