### ISSUE TITLE
Missing letters on the home page

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla/science.mozilla.org#34]
¡Hola!

http://www.mozillascience.org/ is missing letters here on Nightly. There's no H on " elping"... I believe is due to "SyntaxError: expected expression, got '<' www.mozillascience.org:7:0"

¡Gracias!

![mozsience](https://cloud.githubusercontent.com/assets/649262/7620575/75379db8-f986-11e4-9aed-267e78508b9e.JPG)

**Comment by acabunoc** [comment]
After a Hello chat, it looks like this only happens on all Fira Sans text -- might be local corrupted font. Might be something else. Need to test more.

**Comment by acabunoc** [comment]
thansk again @alex-mayorga!

**Comment by hannahkane** [comment]
No longer relevant, given migration to science.mozilla.org.
