### ISSUE TITLE
[design QA] crop thumbnail images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#341]
Can all thumbnail images (project, event, blog thumbnails) automatically crop so they all have the same height and width? Preferably they crop from the center so it would crop equally from the top and bottom or equally on both left and right side?

Staging:
<img width="1229" alt="screen shot 2016-05-10 at 1 31 04 pm" src="https://cloud.githubusercontent.com/assets/1068783/15161554/822e9b98-16b3-11e6-8b9f-abf0f67a60d7.png">
<img width="1202" alt="screen shot 2016-05-10 at 1 31 38 pm" src="https://cloud.githubusercontent.com/assets/1068783/15161569/8f4b8d40-16b3-11e6-9efb-f2e079fc3255.png">

Comps:
<img width="977" alt="screen shot 2016-05-10 at 1 32 11 pm" src="https://cloud.githubusercontent.com/assets/1068783/15161588/a288b8a6-16b3-11e6-88cb-92e9b72898ea.png">

**Comment by alanmoo** [comment]
Only future projects have the image, and there's only one of those for now, so I'm putting this in the backlog. It's hard to apply a blanket paradigm to this and make sure it looks good, so we may want to suggest ratios for images when adding them or something.

**Comment by kristinashu** [comment]
Closing since this is covered in https://github.com/mozilla/science.mozilla.org/issues/468
