### ISSUE TITLE
[design QA] fellowship icon sizes and not showing up

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#342]
The icons should be similar sizes but some of them look too big or too small.

Staging:
<img width="125" alt="screen shot 2016-05-10 at 11 51 34 am" src="https://cloud.githubusercontent.com/assets/1068783/15161718/13391550-16b4-11e6-91b3-762ec3a8321c.png">

Comp:
<img width="287" alt="screen shot 2016-05-10 at 1 34 57 pm" src="https://cloud.githubusercontent.com/assets/1068783/15161771/49402b70-16b4-11e6-9593-ad440f5e8706.png">
<img width="290" alt="screen shot 2016-05-10 at 1 35 05 pm" src="https://cloud.githubusercontent.com/assets/1068783/15161770/493db020-16b4-11e6-8f0c-71a3fc95c2a6.png">

**Comment by kristinashu** [comment]
Also noticed that some icons that look good at full width, start to look weird a narrower browser widths:

Staging - narrow browser width:
<img width="261" alt="screen shot 2016-05-11 at 10 44 57 am" src="https://cloud.githubusercontent.com/assets/1068783/15190728/5c1cf2d4-1766-11e6-80df-06e338233c5c.png">

Staging - wide browser width:
<img width="352" alt="screen shot 2016-05-11 at 10 50 56 am" src="https://cloud.githubusercontent.com/assets/1068783/15190729/5c1e5552-1766-11e6-93cc-3006200aa97d.png">

**Comment by kristinashu** [comment]
Examples above are from FF. The icons look good in Chrome. They don't show up at all in Safari and in FF on iPhone.

Staging in Safari:
<img width="1067" alt="screen shot 2016-05-11 at 4 12 46 pm" src="https://cloud.githubusercontent.com/assets/1068783/15199473/3c50cbd8-1793-11e6-8c2f-7f1e5630b558.png">

**Comment by alanmoo** [comment]
For desktop Firefox, these icons are varying in size according to the number of lines in the row of text to their right.
