### ISSUE TITLE
[design QA] images in body are too big

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#349]
Related to [design QA] grid width for body copy #340 

To avoid massive images, they should use fewer grid columns than the copy.

Staging:
<img width="1051" alt="screen shot 2016-05-10 at 4 58 02 pm" src="https://cloud.githubusercontent.com/assets/1068783/15166232/bf4540cc-16d1-11e6-8a14-a2612912903b.png">
<img width="1252" alt="screen shot 2016-05-10 at 4 58 37 pm" src="https://cloud.githubusercontent.com/assets/1068783/15166233/bf614f42-16d1-11e6-9ce5-c7c0b7f01aa0.png">

Comps:
<img width="1004" alt="screen shot 2016-05-10 at 5 06 27 pm" src="https://cloud.githubusercontent.com/assets/1068783/15166227/b8ba3960-16d1-11e6-971f-d98cad3fa2de.png">
<img width="1006" alt="screen shot 2016-05-10 at 5 05 43 pm" src="https://cloud.githubusercontent.com/assets/1068783/15166229/babb659a-16d1-11e6-84b2-3ffe35be1c26.png">

**Comment by alanmoo** [comment]
I've given a swing at solving for this in #430, @kristinashu this should be merged into staging by the time you're back. I could only address the images at the top of the event pages, non-text content in the body of the event details has other variables at play that make it more difficult to quickly solve.

Please take a look at it (at various viewport sizes) and let me know your thoughts.

**Comment by kristinashu** [comment]
Looks good, thanks @alanmoo!
