### ISSUE TITLE
Copy and link updates to Fellowship pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#350]
Before launch we will need to:
- [x] update Apply Now button link to the screen door form link (need link)
- [x] update copy in bottom section to "Deadline for applications is July 15, 2016"

<img width="1220" alt="screen shot 2016-05-11 at 9 54 19 am" src="https://cloud.githubusercontent.com/assets/1068783/15189291/a7bd94ee-175e-11e6-8578-d55becd79c9d.png">

**Comment by alanmoo** [comment]
@acabunoc What's the screen door link? This will be hidden, but I want to add it all in now so it's easier to unhide before launch.

**Comment by acabunoc** [comment]
https://github.com/mozilla/science.mozilla.org/issues/375#issuecomment-219864757
