### ISSUE TITLE
[design QA] add equation to home page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#357]
Home page is missing the + and = 

Staging:
<img width="1337" alt="screen shot 2016-05-11 at 3 44 45 pm" src="https://cloud.githubusercontent.com/assets/1068783/15198923/76c7bcb2-178f-11e6-8818-094320bf89fd.png">

Comp:
<img width="1239" alt="screen shot 2016-05-11 at 3 45 17 pm" src="https://cloud.githubusercontent.com/assets/1068783/15198922/7507842a-178f-11e6-925a-25df746b3e0e.png">

**Comment by gvn** [comment]
Looks like the CSS is there in `home.scss` and must have gotten lost in a ThreeUp refactor.

**Comment by alanmoo** [comment]
I'm guessing the same refactor shrunk those icons
