### ISSUE TITLE
Update three-up component once Bootstrap 4 is updated

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#359]
This is just kind of a note for the future:

While exploring I realized that with the next update to Bootstrap there will need to be updates to three-up's styles. `make-col` and `make-col-span` become one mixin, a few styles need to be refactored.

The new signature is `@include make-col($size, $columns: $grid-columns, $gutter: $grid-gutter-width)`, at least on https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_grid.scss#L36. When we get around to this we may need to double check that.

**Comment by alanmoo** [comment]
(Blocked until Bootstrap v4 releases a new tag)

**Comment by alanmoo** [comment]
I believe this update has been released, so Mofo-Bootstrap can be updated to reflect this now

**Comment by HassenPy** [comment]
three-up seems to no longer use `make-col`.

**Comment by alanmoo** [comment]
Good point, looks like this is unnecessary. Thanks for pointing that out!
