### ISSUE TITLE
Close fellows applications for website launch

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#374]
We should launch the site without the call for Fellows

- [x] Hide the 'apply to be a fellow' hero images on the homepage
- [x] Hide the 'Apply Now' block on Fellows pages

**Comment by alanmoo** [comment]
Should the top CTA change too? `Are you a champion of open science and open data? Mozilla is seeking researchers eager to advance openness in science and data within their institutions.`

**Comment by acabunoc** [comment]
@alanmoo I think it's fine! We could change 'Appy Now' to 'Applications open on June 3'
