### ISSUE TITLE
Copy Changes for fellows application launch!

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#375]
June 3!

@auremoser can provide links to screendoor for applications

**Comment by auremoser** [comment]
Status update:
* screendoor subscription is being processed w/dev ops
* until then, I won't have the link but I'll get it to you before (hopefully) the 20th.

Thanks!

**Comment by auremoser** [comment]
### Content Update:

All content for the new fellow CFP is available in these documents, request access if you need them ahead of time:

* [2016 CFP Landing Page Copy](https://docs.google.com/document/d/1CpeoT-gJjapZ54HG_-2AqxIIYmNnpoF2p995WZrbjOc/edit#)
* [2016 FAQ](https://docs.google.com/document/d/1iE-UAM1-8DABBF4ynGBSz6gHw4jCnZtFZnz57nyJQGk/edit#)
* [2016 Application Questions](https://docs.google.com/document/d/1_JAhRYZKYgHpvHJIVUKiWDuMMcLjHLuAvVmRqX8AaAc/edit?ts=57324cd1)

I'm adding all of the above content to the screendoor application, like this [2015 one](https://mozilla-science-lab.forms.fm/mozilla-fellows-for-science-2015) which we will link to from our website's call to action, if there is any other copy that needs to be written I can cull it from these documents. 

I'll send an update later today. 

### Launch Update
I'm storing some notes and a timeline [here](https://docs.google.com/document/d/1unynVpuyHw7azddm-upTAQgT6C1Q0VbOlX476JgwK2M/edit?ts=5735fd33#heading=h.z27769jbcosl), with a hopeful CFP launch date of **June 3rd** (with website), though for bug fixing sake I'm officially (in listserv announcements, newsletters, general email) pushing this to **June 6th** (the Monday after launch).

If any of the above is bad/problematic, let me know.

cc/ @alanmoo + @hannahkane

**Comment by auremoser** [comment]
Addendum: When I said "June 6th" I meant that I'm suggesting people visit the application on the Monday after the launch of the site, just in case we want to let the site breathe for a few days before we up the traffic.

**Comment by auremoser** [comment]
O.k., content is complete for the application, embed the form via the code below, or just link to it via the link included below. It is **not live yet**, I'll push it live on the 3rd, but the details below will be the same.

Link: <https://mozilla-science-lab.forms.fm/mozilla-fellows-for-science-2016>

Embed:
```
<!--
  If possible, insert the following lines into the page <head>.
-->

<script>window.jQuery || document.write('<script src="//code.jquery.com/jquery-2.2.3.min.js"><\/script>')</script>

<link href="//d3q1ytufopwvkq.cloudfront.net/0/formrenderer.css" rel="stylesheet" />
<script src="//d3q1ytufopwvkq.cloudfront.net/0/formrenderer.js"></script>

<!-- Insert everything below in the <body>. -->

<form data-formrenderer>This form requires JavaScript to complete.</form>

<script>
  // Uncomment this line and set it to the CSS class that your website uses for buttons:
  // FormRenderer.BUTTON_CLASS = '';

  new FormRenderer({"project_id":"dVXu1wk3l0dxsFJy"});
</script>
````

Where is the best place to add the FAQ content, in the website directly via my login, or elsewhere @acabunoc ?

**Comment by alanmoo** [comment]
Can we just link to that page come June 3? I don't think there were plans to embed it.

**Comment by auremoser** [comment]
Yep, that's why I including the link.

**Comment by acabunoc** [comment]
The fellowship copy needs to be updated on the new site by the front-end team for the June 3 launch. Copy in the docs below

* [2016 CFP Landing Page Copy](https://docs.google.com/document/d/1CpeoT-gJjapZ54HG_-2AqxIIYmNnpoF2p995WZrbjOc/edit#)
* [2016 FAQ](https://docs.google.com/document/d/1iE-UAM1-8DABBF4ynGBSz6gHw4jCnZtFZnz57nyJQGk/edit#)

**Comment by alanmoo** [comment]
These changes are in and visible at https://science-mozilla-org-sta-pr-442.herokuapp.com/ - this still mentions the application launch being June 3, is there any reason to not update the FAQ and such until then? Or can we merge this in and then file another ticket to change the links on the 3rd?

**Comment by acabunoc** [comment]
This is great @alanmoo! Yes, I think merging this in + another ticket to change the links on the 3rd is a good plan.

**Comment by auremoser** [comment]
+1
