### ISSUE TITLE
Projects hero links missing

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#388]
http://science-mozilla-org-staging.herokuapp.com/projects

The links in `Have a project you want to add?Bring it to our Global Sprint, Mozfest, or Working Open Workshop.` need wiring up.

Also there should be a space after the `?`.

**Comment by alanmoo** [comment]
What I'm guessing for links:

Global Sprint: programs/events/global-sprint-2016
Mozfest: https://mozillafestival.org/
Working Open Workshop: ?? @acabunoc

**Comment by acabunoc** [comment]
working open workshop *should* be: http://science-mozilla-org-staging.herokuapp.com/programs/programs/events/working-open-workshop-february-2016 -- but it doesn't seem to be loading

**Comment by acabunoc** [comment]
nevermind, there was a double 'programs': http://science-mozilla-org-staging.herokuapp.com/programs/events/working-open-workshop-february-2016

I got there from the events page, so that's odd

**Comment by alanmoo** [comment]
@acabunoc That fix is already built, will deploy with these changes in #396
