### ISSUE TITLE
Switch to git flow

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#390]
Git flow reference: http://nvie.com/posts/a-successful-git-branching-model/

- [x] add `develop` branch and set as default
- [x] map `develop` branch to [staging server](http://science-mozilla-org-staging.herokuapp.com/) and set up CI
- [x] add production/release-candidate server to Heroku, which pulls from `master`
- [x] point production/release-candidate to the production API once it's ready & migrated
- [x] map `master` branch to release candidate server (will become production) and set up CI

cc: @alanmoo @alicoding @gideonthomas @acabunoc

**Comment by gideonthomas** [comment]
All set up!

**Comment by gvn** [comment]
![itclap](https://cloud.githubusercontent.com/assets/206379/15338820/6cc9f896-1c36-11e6-86b9-112c504646dd.gif)
