### ISSUE TITLE
wp.mozillascience.org lacks https

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#395]
Right now there are mixed content warnings on https://science-mozilla-org-production.herokuapp.com/blog because `wp.mozillascience.org` is being accessed over `http`.

Can we add SSL to wp.mozillascience.org?

CC: @acabunoc

**Comment by acabunoc** [comment]
There's SSL on https://mozscienceblog.wpengine.com/ -- we can update all the links from wp.mozillascience to mozscienceblog.wpengine.com

**Comment by gvn** [comment]
Is the wordpress API under a different path on mozscienceblog.wpengine.com?

I tried `https://mozscienceblog.wpengine.com/posts?cachebuster=592515951852.9949&page=1` and it doesn't resolve.

**Comment by gvn** [comment]
Ok, I think this is working under: https://mozscienceblog.wpengine.com/wp-json
