### ISSUE TITLE
QA the v1

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#399]
Hoping the Science team can help QA this week.

This means looking at the staging site, and filing bugs for:
 * Bad copy (forgotten placeholder copy, typos)
 * Broken links (including header, footer, and all page content)
 * Bad data - i.e. projects, resources, and events should look accurate and complete (@gideonthomas to advise on when the staging server is pointing to production-ready data)
 * Broken functionality (i.e. search and filter work on Projects and Resources; Study Group submit form works as expected; newsletter sign up)
 * Broken interactivity (e.g. "See More" button on Resources and Blog)
 * Looks good and is functional on multiple browsers and devices

Thank you for helping us try to break stuff! Please file issues and put "[QA]" in the issue title. For things that need to be fixed before launch (e.g. usability issues, typos), please feel free to put them in the May 20th heartbeat. But also file things that you think aren't urgent but should eventually be fixed (e.g. design bugs that don't affect usability).

@gvn @alanmoo @alicoding @gideonthomas - feel free to amend the above as you see fit

**Comment by hannahkane** [comment]
@auremoser @zee-moz @stephwright @kaythaney - do any of you have time to help QA this week? Or suggestions for community members we might call on to help with this? thanks!

**Comment by hannahkane** [comment]
@kgorr's going to help out as well. Thanks, Kristina!!

**Comment by auremoser** [comment]
I can help but not until Friday, I'll set aside some time. Thanks @hannahkane

**Comment by stephwright** [comment]
I can help too but not til Thursday.  I'll block off some time, as well.  I know I have the link to the staging site somewhere but do you mind putting it in here for easy reference?

**Comment by hannahkane** [comment]
Thanks @auremoser and @stephwright. Staging is here: http://science-mozilla-org-staging.herokuapp.com/

**Comment by gideonthomas** [comment]
I believe that QA is happening on https://science-mozilla-org-production.herokuapp.com/ (@alanmoo can you confirm this assertion).

@auremoser for any data changes that need to happen directly in the API, you can use https://api-mozillascience-production.herokuapp.com/admin for them. Your previous username/password should work on there too.

**Comment by alanmoo** [comment]
@gideonthomas No, it's happening on staging as Hannah linked. That's where merges into the develop branch automatically deploy so it gets updates faster.

**Comment by gideonthomas** [comment]
@alanmoo so should staging point to the production API?

**Comment by alanmoo** [comment]
It probably should until launch for easier QA, then we can split it to point to the staging API.

**Comment by auremoser** [comment]
Thanks @gideonthomas + @alanmoo !

**Comment by KGorr** [comment]
@hannahkane, do all of the projects and resources need QA'd, or just the page they are housed on?

**Comment by alanmoo** [comment]
Anything that's on that same herokuapp domain should be QA'ed

-Alan

**Comment by stephwright** [comment]
In an effort not to duplicate... uh, efforts, heads up I'm working on Fellows pages right now.

**Comment by stephwright** [comment]
Also reviewed Global Sprint page.  Is there some other way I should be tracking this so we're not all reviewing the same pages w/o reviewing others?

**Comment by KGorr** [comment]
To help others see what I've noted, I filed this ticket: https://github.com/mozilla/science.mozilla.org/issues/416

@hannahkane - if it needs divided into different tickets, let me know!

**Comment by stephwright** [comment]
Yer awesome @KGorr !!!  Thanks!

**Comment by hannahkane** [comment]
I'm closing this because several people have had a chance to review the site and file tickets. More reviewers/tickets are welcome!
