### ISSUE TITLE
Tags or categories visible on blog

### ISSUE THREAD

**Issue by BillMills** [mozilla/science.mozilla.org#40]
I tried setting tags and categories on the latest blog post per @kaythaney's request, but I don't see them appearing anywhere on the post (like so people can navigate to a list of just that tag / category).

**Comment by acabunoc** [comment]
This and #17 are artifacts of our unintended use of wp...

**Comment by hannahkane** [comment]
Closing as part of a sweep to clean up tickets applicable to the old Science site
