### ISSUE TITLE
[QA] Several links in fellows bios are broken or point to wrong place

### ISSUE THREAD

**Issue by stephwright** [mozilla/science.mozilla.org#411]
http://science-mozilla-org-staging.herokuapp.com/programs/fellowships
Under Joey:
* Link to "Big Atlas of Pools" results in 404
* "building workshops" link points to a slide halfway through the presentation
* same w/ "between his MSc research"

Under Richard:
* Solver.io has bad certificate - talkiing to Richard now, he's going to create a landing page because Solver.io "doesn't exist anymore".  Maybe just remove link right now?

**Comment by alanmoo** [comment]
Could Solver.io link to https://github.com/solvers ?
