### ISSUE TITLE
[QA] Need to update some content in Fellowships Overview

### ISSUE THREAD

**Issue by stephwright** [mozilla/science.mozilla.org#412]
http://science-mozilla-org-staging.herokuapp.com/programs/fellowships
"About the Program"
- [ ] 2nd para: "Fellows will spend 10 months starting September 2015" - suggest removing year
- [ ] inconsistent use of Oxford comma throughout text (no biggie, just caught my eye :) )
- [ ] some of the graphic bullets under throughout the page look significantly bigger than others

**Comment by stephwright** [comment]
Just found out all the copy is a placeholder while getting application up & running.  Removing Milestone for this heartbeat.

**Comment by hannahkane** [comment]
Closing this, as all of these are now referenced in other tickets. Thanks for the eagle eye!
