### ISSUE TITLE
[QA] Incorrect dates on Global Sprint event

### ISSUE THREAD

**Issue by stephwright** [mozilla/science.mozilla.org#414]
Global Sprint is June 2-3, not 1-3

**Comment by alanmoo** [comment]
I wonder if this has something to do with time zones...

**Comment by gideonthomas** [comment]
Yeah I'm pretty sure! In the database, the time is stored as "2016-06-02T06:00:00Z"

**Comment by alanmoo** [comment]
I've addressed this in a PR- when rendering a date range I'll use UTC for the dates. We're going to have to keep an eye on this when we get to form submission for events.
