### ISSUE TITLE
[QA] Homepage/Fellowships/Study Groups

### ISSUE THREAD

**Issue by KGorr** [mozilla/science.mozilla.org#416]
**Homepage**
What’s new section – nothing is linked

**http://science-mozilla-org-staging.herokuapp.com/programs/fellowships**

All Tabs
- [x] Apply now button not working (both instances)
- [x] Under 2nd apply now button it says “Deadline 11:59pm PT [date], 2016” 

Fellows Tab
- [x] Fellows is capped in 1st paragraph, but no where else
- [x] I get a “Your connection is not secure” message from Richard Smith-Unna’s Solvers.io link.
- [x] http://jk-lee.com/The-Big-Atlas-of-LA-Pools link is not working under Joey Lee

Overview tab
- [x] 2nd paragraph: “Fellows will spend 10 months, starting September 2015, as community catalysts”
- [x] Last paragraph under fellow responsibilities, I think “buy in” should be hyphenated…
- [x] Under Stipend section, fellowship and Fellows is capped I the 1st sentence, then it’s not for a bit, then it starts being capped again.
- [x] Who can become a fellow bullet 5: should “As fellows” be “all fellows”

FAQ tab
- [x] Next to last Q “We want to make sure Fellows, as they'll be working somewhat autonomously within their institution, are in supportive environments.”

- [x] I would take out the smiling face and extra space in the last Q

**http://science-mozilla-org-staging.herokuapp.com/programs/studygroups#**
- [x] Under Run a Study Group tab “lessons” is sometimes capped and sometimes not

- [ ] Journal Club Lessons – something is wrong with this sentence. I think maybe the “or” should be removed? “Journal club lessons are like reading or book club templates for scientific papers, an alternate option to code curricula for Study Group meetings.”

- [ ] Journal Club: Code Review – last sentence is missing ending punctuation

- [ ] Study Group Lesson Index - last sentence is missing ending punctuation

- [ ] Resources tab – the sentence in the header image should wrap with more than 3 words on the 2nd line.

**Comment by KGorr** [comment]
Oh, and super-picky find: throughout the whole site, the oxford comma is used and not used about 50/50. I didn't note all instances because I'm not sure which should be used.

**Comment by gvn** [comment]
@KGorr Is fellows supposed to be capitalized?

**Comment by KGorr** [comment]
@gvn - I'm not the authority on it (just helping), but it seemed to NOT be capped more often than capped. Not sure who to ask for verification...

**Comment by gvn** [comment]
@hannahkane Do you know who can clarify what needs to happen in this ticket?

**Comment by hannahkane** [comment]
Let's not capitalize "fellows."

Not sure about the rules on Oxford comma (personal preference: yes!), but let's not worry about fixing those for May 20.

**Comment by hannahkane** [comment]
cc @KevZawacki who I think has a vision of someday having a written styleguide for Mofo. The above could provide fodder for that.

**Comment by hannahkane** [comment]
we can also not capitalize "fellowship" except for when it's used formally as in the "Mozilla Fellowships for Science".
