### ISSUE TITLE
change IRC link in footer to a chat channel

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#418]
Not sure which one. @acabunoc - is there an MSL channel?

**Comment by acabunoc** [comment]
http://gitter.im/mozillascience/community

But we mirror content from here to our irc channel

**Comment by hannahkane** [comment]
in that case, we can leave as is if you'd prefer. I just thought maybe a switch had been made to chat.mofo.

will close, but re-open if you prefer the gitter link.

**Comment by acabunoc** [comment]
I prefer the gitter link! Thanks :)

**Comment by gvn** [comment]
@acabunoc were you planning on doing a PR, or should Alan or I take this?
