### ISSUE TITLE
font in the footer menu making confusion with the letter 'C' and 'E'

### ISSUE THREAD

**Issue by amjadm61** [mozilla/science.mozilla.org#42]
The letter 'E' and 'C' is almost same for the font used in the footer menu. The letter 'E' is almost same as the letter 'C'. So, it would be better to use some other good font to resolve this issue.

**Comment by acabunoc** [comment]
Thanks @amjadm61! I'm not sure I'm seeing the same problem - can you add a screenshot?

![screen shot 2015-08-05 at 11 53 41](https://cloud.githubusercontent.com/assets/617994/9090521/a56c79da-3b68-11e5-8b79-fc7140e78890.png)

**Comment by amjadm61** [comment]
![capture](https://cloud.githubusercontent.com/assets/4783625/9150751/fcb28152-3e07-11e5-9af7-6ec009f2cc89.PNG)

This is from Firefox 39.0

**Comment by acabunoc** [comment]
Hey @amjadm61 - are you on windows / mac? Thanks!

**Comment by acabunoc** [comment]
For reference to try based on response:

    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;

http://stackoverflow.com/questions/11459746/webfont-smoothing-and-antialiasing-in-firefox-and-opera

**Comment by amjadm61** [comment]
I'm really sorry acabunoc, I was very busy with my job in the past days. So, I couldn't able to reply to this thread on time :-(
btw, I'm using windows 7 OS. and the issue is seems like not resolved yet.

**Comment by acabunoc** [comment]
@amjadm61 no worries! This helps, thank you :)

**Comment by mmhyamin** [comment]
**OS:** Windows 7 Ultimate Service Pack 1
**Browser:** Firefox 39.0
[Screenshot](https://www.screencast.com/users/mmhyamin/folders/MSL/media/5e2fc536-7a6b-4ee7-bb4f-a9a7bb04c899)

After installing Fira Sans locally, [Screenshot](https://www.screencast.com/users/mmhyamin/folders/MSL/media/a2295677-93e4-4183-965c-73df4cc30f7b)

**Comment by mmhyamin** [comment]
I found a bug related to FiraSans: [FiraSans and FiraMono appear blank](https://github.com/google/fonts/issues/10)

**Comment by mmhyamin** [comment]
Duplicate Bug: [Missing letters on the home page](https://github.com/mozillascience/site/issues/34)

**Comment by hannahkane** [comment]
This is no longer relevant, given the migration to science.mozilla.org. Thanks for filing!
