### ISSUE TITLE
OpenMetaAnalysis name

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#425]
The data in https://api-mozillascience-staging.herokuapp.com/projects/27/ has a long name with no spaces causing rendering issues. Should it...not be a url? Or should I force wrap mid-word on titles?

**Comment by acabunoc** [comment]
updated to openMetaAnalysis -- does this fix things?

**Comment by alanmoo** [comment]
That is to say, it would solve it, but I'm not seeing that on prod or staging

**Comment by acabunoc** [comment]
Ah, @gideonthomas it won't let me save without changing the slug:
![screen shot 2016-05-20 at 13 22 21](https://cloud.githubusercontent.com/assets/617994/15441131/f7f182c8-1e8d-11e6-948b-ec04ebfdfe04.png)

**Comment by gideonthomas** [comment]
@acabunoc Unfortunately that is not a valid slug name because of the punctuation (https://en.wikipedia.org/wiki/Semantic_URL#Slug). Have you tried just having the slug as `openMetaAnalysis`?

**Comment by acabunoc** [comment]
We could but then redirects won't work properly

**Comment by gideonthomas** [comment]
alright, I'll try to add an exception for the period character.

**Comment by gideonthomas** [comment]
@acabunoc how bad would it be if we added an exception on the redirect instead and change the slug to `openMetaAnalysis`? That is to say, `mozillascience.org/projects/jstirnaman-openMetaAnalysis.github.io` will redirect to `science.mozilla.org/projects/openMetaAnalysis` and everything else will redirect normally? 

It seems like a bit of a rabbit hole trying to add exceptions for periods and I'd like to implement it only if the custom redirect will create issues.

**Comment by acabunoc** [comment]
Either option works! But currently our slugs are generated from the github repo name - which often contain a period. I we do the one off redirect, we'll need to update how we generate slugs.

**Comment by gideonthomas** [comment]
Yep, any new project that is created won't have this problem.
I'll identify the projects/events that need this change for now.

**Comment by gideonthomas** [comment]
**Note to self**: When we set up redirects to the new site, add the above mentioned redirect exception.
`openMetaAnalysis` seems like the only one that requires this exception.

**Comment by acabunoc** [comment]
Updated!

**Comment by gideonthomas** [comment]
I'm going to close this since we're tracking the last part of this, i.e. the redirect exception, in the devops repo.
