### ISSUE TITLE
Front-end QA

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#435]
Let's coordinate front-end QA.

**Comment by hannahkane** [comment]
I can look at every page of the site on an iPhone/Safari. Is that helpful, @gvn @alanmoo ?

**Comment by gvn** [comment]
Yes, I think that we should all go through with our phones/devices.

I have a Nexus 5, iPad, and some other random phones.

**Comment by alanmoo** [comment]
I've got an iPhone 6 and Nexus 4

**Comment by hannahkane** [comment]
Finished going through on an iPhone 5. Didn't find anything that hadn't already been filed.

**Comment by hannahkane** [comment]
Closing this.
