### ISSUE TITLE
Display glitches in accordion

### ISSUE THREAD

**Issue by gvn** [mozilla/science.mozilla.org#438]
On an iPad w. Safari there are display glitches when using the accordion.

Repro: expand & collapse a few items.

**Comment by hannahkane** [comment]
I'm seeing this on iPhone 5 with Safari. Same thing?

![img_1085](https://cloud.githubusercontent.com/assets/8389648/15522857/436e5da4-21ca-11e6-827d-7befbfb5cfca.PNG)

**Comment by alanmoo** [comment]
@kristinashu We're reverting this back to 1 column across browser right now because it's being rather buggy- may attempt to re-implement as 2 columns later.

**Comment by alanmoo** [comment]
This was fixed by #444, right @gvn?

**Comment by gvn** [comment]
Yes, verified on iPad on staging.

**Comment by kristinashu** [comment]
1 column is good for now but it would be great to eventually make it 1 column at small widths and 2 column on wider screens

**Comment by alanmoo** [comment]
Yeah, I tried that but the tech isn't quite there to make it easy- it's going to be more involved to get a solution that works today.
