### ISSUE TITLE
Create promotional image for Twitter

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#448]
We'll be announcing the new site design and url on Twitter. Would be great to have an image to accompany. Could be screenshot of homepage with text of url. Open to other ideas! :)

**Comment by kristinashu** [comment]
@acabunoc here's an image for the tweet. Let me know if that works for you.
![science-twitter](https://cloud.githubusercontent.com/assets/1068783/15655049/2472387a-264e-11e6-9ba0-e06a10833316.jpg)

It might also be worth saying something, maybe in a separate tweet, that authentication is temporarily disabled. Wouldn't want anyone to think their account is lost.

**Comment by acabunoc** [comment]
Thanks @kristinashu! Good idea for the disabled account tweet

**Comment by kristinashu** [comment]
Closing this but let me know if you need any other images.

**Comment by hannahkane** [comment]
cc @KevZawacki

**Comment by KevZawacki** [comment]
@kristinashu @hannahkane 

Perfect! Thank you kindly 😄
