### ISSUE TITLE
[design QA] add more padding

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#449]
The site generally needs a little more vertical space in some areas to make it feel more airy and for better legibility.
- [x] **Home page Events/StudyGroups:** 
  Make blue + purple background taller (more padding between the button and the What's New background image).

Staging:
<img width="1326" alt="screen shot 2016-05-25 at 2 17 51 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556617/9ab8ad94-2283-11e6-8355-5784582ee55a.png">

Comp:
<img width="1239" alt="screen shot 2016-05-25 at 2 05 51 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556517/17f92366-2283-11e6-8ef1-e64ab2fd486b.png">
- [x] **Home page What's New:** 
  Make background taller (more padding above and below content).

Staging:
<img width="1326" alt="screen shot 2016-05-25 at 2 18 02 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556631/c176df46-2283-11e6-9582-a5a4011f0acd.png">

Comp:
<img width="1239" alt="screen shot 2016-05-25 at 2 06 05 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556519/17fe0642-2283-11e6-8eb5-74cf81ae29ac.png">
- [x] **Add padding above footer:** 
  Increase the space above the footer and make it more consistent across pages.

Staging example: Study Group page should have more space between 'Don't see one near you?" text and the purple background

<img width="1328" alt="screen shot 2016-05-25 at 2 06 35 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556687/11e80658-2284-11e6-8e98-9e4e94cdec46.png">

Staging example: event details
<img width="1381" alt="screen shot 2016-05-25 at 2 11 04 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556872/f7fb7bb6-2284-11e6-930d-7897909e0b03.png">
- [x] **Study Group Form:** 
  Add padding between the form and 'Study Group Lessons' title

Staging:
<img width="1343" alt="screen shot 2016-05-25 at 2 06 59 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556759/752b789e-2284-11e6-88dd-6541ff2f292c.png">

Comp:
<img width="1171" alt="screen shot 2016-05-25 at 2 07 29 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556768/7db54a58-2284-11e6-96b5-99249e8788ac.png">
- [x] **Add padding above and below images:** 

Staging example: blog post images need more padding 
<img width="1333" alt="screen shot 2016-05-25 at 2 10 52 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556814/9fa6ebf8-2284-11e6-9372-6f3d20305c92.png">

Staging example: project details image box needs more padding below
<img width="1344" alt="screen shot 2016-05-25 at 2 09 23 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556829/bce3bbe2-2284-11e6-99c8-8522402a08c5.png">

Comp:
<img width="1214" alt="screen shot 2016-05-25 at 2 10 03 pm" src="https://cloud.githubusercontent.com/assets/1068783/15556860/e5ba3140-2284-11e6-9b00-dcd42bb21ddf.png">

**Comment by narendrashetty** [comment]
@alanmoo I can make these changes and send a PR

**Comment by alanmoo** [comment]
@narendrashetty I had a conversation with @amjadm61 in #481, so make sure you two aren't doing duplicate work

**Comment by alanmoo** [comment]
A note about this- the proper solution likely involves use of the utility classes found [here](http://v4-alpha.getbootstrap.com/components/utilities/#spacing) on the markup for these pages, rather than writing more CSS.

**Comment by narendrashetty** [comment]
@amjadm61 do let me know if you have started the work on this

**Comment by amjadm61** [comment]
@narendrashetty  I'm working on the first 3 issues. So, you can work on the last 2 issues.

have a nice coding.. :)

**Comment by narendrashetty** [comment]
About last issue `add padding above and below images` is on the blog post images, whose content is dynamically appended. cc: @alanmoo @amjadm61

**Comment by HassenPy** [comment]
shouldn't this be closed?

**Comment by alanmoo** [comment]
Yes, it should, thanks for pointing it out!
