### ISSUE TITLE
github contributors not showing up on project pages

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#452]
only the 'lead' and 'volunteers' -- not the actual contributors from the github api

**Comment by kristinashu** [comment]
Flagging that on the current site, contributors and volunteers are duplicated. Ex. Amit on https://www.mozillascience.org/projects/KirstieJane-STEMMRoleModels
Can we not show them twice? 

The current site also distinguishes between contributors (full color picture) and volunteers (grey scale), we don't need to distinguish them so can they all be full color?

@acabunoc does that sound right?

**Comment by acabunoc** [comment]
Thanks @kristinashu, yes that sounds right!

**Comment by alanmoo** [comment]
It appears that github contributors is not a superset of the project's users as seen [here](https://api-mozillascience-production.herokuapp.com/projects/13/), so I think I'm going to have to do this:

* Display project lead
* Display project members
* Display contributors, but filter out project lead/members based on github username matching

And all of this is displayed as photos across the top of the project page, right? Any upper limit on quantity across various screen sizes?

**Comment by acabunoc** [comment]
Slight tweak, can you:

* Display project lead
* Display contributors
* Display project members, but filter out contributors based on github username matching

The project members are just people who clicked 'join project' on the old site. They may or may not have contributed.

**Comment by alanmoo** [comment]
So basically a change in rendering order?

**Comment by acabunoc** [comment]
yes - I forgot we're not displaying them differently here! But also, the github contributors are usually ordered by amount of contributions, so adding volunteers last makes sense

**Comment by kristinashu** [comment]
Sounds good. Yes, all the photos can be displayed across the top. I don't think we'll need an upper limit. 

Also, just to be clear, these will only show up on the detail page. The cards on the landing page are correct the way they are - only showing the project lead(s).
