### ISSUE TITLE
Project Detail page - Institution link isn't working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#455]
If there is an associated Institution, it should link to the external site

If there is no institution then the field should be hidden. Ex. http://science-mozilla-org-staging.herokuapp.com/projects/bigvasp not sure what is happening here but I think "Independent" should not appear.

**Comment by acabunoc** [comment]
I don't think we store a link to institutions in the database, so it might not be possible to link to the external site yet

**Comment by alanmoo** [comment]
So I'll just take the link off?

**Comment by kristinashu** [comment]
Oh ok, yeah just remove the link please
