### ISSUE TITLE
Code of Conduct Link fix

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#466]
### Context
Homepage footer link to Code of Conduct overrides homepage on click: https://science.mozilla.org/code-of-conduct
![screen shot 2016-05-28 at 12 18 44 pm](https://cloud.githubusercontent.com/assets/1559703/15629434/9757a94c-24cd-11e6-9c6c-d10119cf02f8.png)

### Expected Result
Like the other footer links, this link would open a new tab with the code of conduct.

### Current Result
Unlike the other footer links, this one overrides the science.mozilla.org url. Might as well add the target="_blank" to this link too no? I guess it just adds a part of the URL that isn't a total departure for the home site, so maybe that's our policy to not open new tabs when it leads elsewhere on the site.. Feel free to ignore if that's the case.

**Comment by hannahkane** [comment]
Taking this out of the milestone, bc I don't think it's a blocker to launch. 

I don't know that we have an official policy on this, but I feel like not opening new tabs when staying on the same site makes sense. @kristinashu - do you have an opinion?

**Comment by kristinashu** [comment]
I agree, internal links should open in the same tab and external links should be in a new tab so I think it is good the way it is.
