### ISSUE TITLE
Fellowships page puntuation

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#467]
### Context

This may seem bogus as a change, and is possibly my fault for writing the copy, but there's a mixture of punctuation on this page that we should standardize: https://science.mozilla.org/programs/fellowships
![screen shot 2016-05-28 at 12 24 56 pm](https://cloud.githubusercontent.com/assets/1559703/15629519/3ac00a2e-24cf-11e6-8a83-cd3bef19d3aa.png)

### Expected Result
All bullet pointed items either have a period at the end, or they don't.

### Current Result
There's a mix of punctuation, we should just pick whatever makes the most global sense and go with it; since most are half-sentences, capitalized event though they supposedly continue a phrase, I vote for no period at the end. Assign this to me and tell me where to push it changes if this (and any other bugs, seem too trivial).

**Comment by hannahkane** [comment]
Thanks, @auremoser. I'm going to take this out of the June 3 milestone, because we're reserving that for things that would block the launch of the site, and I don't think this should. Though, of course, we can do this if anyone has time.

I'd also vote for no period.

**Comment by alanmoo** [comment]
Ah, right, I meant to comment on this when I submitted the original PR. The other related issue is continuity with the verbiage from the top: "Fellows must be: Have the ability to accept..." Doesn't quite flow :). @auremoser  Would you rather "Fellows must: " or "Fellows must be:"?

**Comment by auremoser** [comment]
Totes, good point @alanmoo, let's change the following:

> Have the ability to accept outside funds for this fellowship directly

to : "Able to accept outside funds for this fellowship directly"

> Have experience participating in open communities.

to: "Experienced participants in open communities"

You can keep the "Fellows must be:" bit

**Comment by karanjthakkar** [comment]
@auremoser I can give this a go if you are ok with it?

**Comment by alanmoo** [comment]
I say go for it. Let me know if you have any issues getting the project running locally.

**Comment by karanjthakkar** [comment]
@alanmoo `main.scss` imports some files from `bootstrap` but `bootstrap` is not given as a dependency anywhere in `package.json`. Am I missing something?

**Comment by alanmoo** [comment]
@karanjthakkar `Mozmaker` is a customized version of bootstrap that we use. It installs bootstrap as a dependency.

**Comment by karanjthakkar** [comment]
@alanmoo I keep getting this error:

<img width="1279" alt="screen shot 2016-06-02 at 8 40 21 pm" src="https://cloud.githubusercontent.com/assets/1824298/15750043/760ac3ee-2902-11e6-80db-c10449486f15.png">

Its trying to find `bootstrap` inside the root `node_modules` folder whereas it is installed inside `node_modules/mozmaker/node_modules`. Do I have to change the `@import` path inside `main.scss` to make this work?

**Comment by karanjthakkar** [comment]
@alanmoo Ok so I temporarily changed the path to look inside `mozmaker/node_modules`. Then it had some issue finding `autoprefixer` so I installed it locally and the project is running now. 😥 I'll send a PR shortly although there is something broken in the setup process I think.

**Comment by alanmoo** [comment]
Ah, I think you might be running an older version of npm- they changed the way dependencies install in npm 3, I believe.

**Comment by karanjthakkar** [comment]
I'm on `npm 2.14.12` and `node 4.3.1`. Probably thats the issue.

**Comment by alanmoo** [comment]
Yup, npm 3 flattened the dependency tree on install, so everything goes into the root `node_modules`. I've submitted #482 so that this is clearer to contributors in the future (their console will alert them, at least), thanks for the feedback!

**Comment by karanjthakkar** [comment]
@alanmoo Thanks for #482. Should definitely help any future contributors.

**Comment by auremoser** [comment]
Surely @karanjthakkar , thank you! I'm sorry for the late reply @alanmoo
