### ISSUE TITLE
Uneven cards + image sizing question

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#468]
### Context
QAing the events page and I noticed that in full-screen mode, the top two events (featuring images and tags) are "uneven".

![screen shot 2016-05-28 at 12 33 33 pm](https://cloud.githubusercontent.com/assets/1559703/15629560/92ee07fe-24d0-11e6-9cfc-c34f7a0e9e3b.png)

### Expected Result
I would expect the images to bloat to the same sizing, so that they would be "even" in how the bottom of each image lines up when they are side-by-side.

### Current Result
The images are slightly off, emphasized by the tags below the image which follow suit. It's visually distracting but not devastating, and my reason for asking is mostly: is there a size that we should make all images so they "match" where possible? I'm happy to conform to a style guide.

Thanks for reading.

**Comment by alanmoo** [comment]
This is indeed something that would benefit from some sort of standardization; attempting to automatically crop everything might result in some weird results. This issue is also seen in projects, where the art for each one is different and the issues with that can be seen in the card view and the project details page. @kristinashu maybe you can provide some input?

**Comment by kristinashu** [comment]
It would be a little mind-numbing, but I would also find it very satisfying, if I went through all the images and cropped them so they all have the same dimensions (and while I'm at it I could replace some of the low res or uninteresting images). @alanmoo would there be an automated way to gather all the images and them re-upload them once I've cropped them?

Then I could set up guidelines and a template for all future image uploads. Although it still might be beneficial to have an auto crop as a back up.

**Comment by alanmoo** [comment]
Separate from actually doing the image processing, I just meant maybe you can help figure out an aspect ratio that works, @kristinashu. We could surely try to batch process them as a first pass and see how they turn out, though I think @acabunoc has access to the images from s3, so she might be able to help. There's probably a command line tool we can run to crop/pad as necessary.

**Comment by acabunoc** [comment]
They're all in the s3 bucket @gideonthomas setup `mozillascience-org-assets`

**Comment by kristinashu** [comment]
All Project, Event, and Blog thumbnails should be 16:9

**Comment by auremoser** [comment]
Beyond 16:9 are there measurements we should stick to when we update images on the site?

Also, @alanmoo right on, you can batch process a whole directory of them in Adobe Bridge, I used to do that at my old job, though the lack of human QA might also affect it.

Sorry to add such a lame issue :(.

**Comment by kristinashu** [comment]
Thumbs are 455px X 256px but they also show up in the Event or Blog post detail page at 616px X 347px so image should be cropped to the larger size. But Project thumbs only show up at the smaller size 455px X 256px. 

@alanmoo are we using retina images for these? If so then we would need to double those dimensions.

**Comment by auremoser** [comment]
Thank you @kristinashu, really helpful. I'm going to bookmark this for future ref.

**Comment by amjadm61** [comment]
any update on this issue?

**Comment by acabunoc** [comment]
Hey @amjadm61 - I'm following the 16x9 rule for future events which should help in the meantime.

**Comment by alanmoo** [comment]
@kristinashu We could use either 1x and 2x images, or just somewhat highly compressed 2x images.

**Comment by hannahkane** [comment]
Closing since there's a manual workaround
