### ISSUE TITLE
What is open source, explanation

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#469]
### Context
Content explaining open source might be too long, or maybe confusing here: https://science.mozilla.org/projects

![screen shot 2016-05-28 at 12 43 42 pm](https://cloud.githubusercontent.com/assets/1559703/15629594/bed53076-24d1-11e6-8d20-00a4590a522d.png)

### Expected
I guess it would be nice if the text matched, and if the open source description was simpler, now that I'm seeing it in context with the other callouts in that section:

> Open source describes software that can be used, modified, distributed, and is collaborative in nature. The extent of its "openness" is determined by the license attached to the software.

### Current

The current one is missing some commas and is a little long:

> Open source describes software that can be used modified and distributed. The extent of its "openness" is determined by the license attached to the software, but in general, open source projects are collaborative in nature, with many people contributing to the source code.

**Comment by acabunoc** [comment]
The current copy is taken from: https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#heading=h.60442fz4wsu3

**Comment by auremoser** [comment]
yep, i guess no need to shorten it if you'd prefer not to...just a suggestion.

**Comment by acabunoc** [comment]
Hey, no preference - added link for context with recently submitted pr
