### ISSUE TITLE
odd <ul> styling on project pages

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#471]
https://science.mozilla.org/projects/brian-bot-githubr

List text seems really big

![screen shot 2016-05-30 at 16 25 57](https://cloud.githubusercontent.com/assets/617994/15657870/356b9272-2683-11e6-9815-f0dd30d7593d.png)

**Comment by alanmoo** [comment]
This stems from Mozmaker using font-size: 1.2rem for all `li`. I've reset that in some cases, but I think across this project we should just reset `li{font-size:1em}` so it's the same as its siblings. Thoughts, @gvn?

**Comment by karanjthakkar** [comment]
@alanmoo I tried playing around with this. Does this look better?
<img width="972" alt="screen shot 2016-06-02 at 6 39 53 pm" src="https://cloud.githubusercontent.com/assets/1824298/15745836/87b085d6-28f1-11e6-8609-c78ab6cd6c77.png">

**Comment by alanmoo** [comment]
Looks good, go ahead and submit a PR so I can spin up a review app and check out the code!

**Comment by acabunoc** [comment]
Just in case, I thought I'd mention that this also shows up on blog posts (but I think you're working on a project-wide fix, so yay)
https://science.mozilla.org/blog/2016-fellows-cfp

![screen shot 2016-06-06 at 15 44 20](https://cloud.githubusercontent.com/assets/617994/15835356/958e5944-2bfd-11e6-8678-9f6f2c79f80d.png)

**Comment by akshatnitd** [comment]
Can I work on this issue?

**Comment by karanjthakkar** [comment]
@akshatnitd Go ahead. I wont be able to work on it.

**Comment by akshatnitd** [comment]
@karanjthakkar What exactly needs to be done for this issue?

**Comment by alanmoo** [comment]
This has already been addressed by an upgrade in MoFo-Bootstrap.
