### ISSUE TITLE
What is /programs?

### ISSUE THREAD

**Issue by cadecairos** [mozilla/science.mozilla.org#476]
When I was putting together the redirect rules for mozillascience.org routes, @acabunoc and I discovered that `/programs` doesn't appear to do anything?

https://github.com/mozilla/science.mozilla.org/blob/4edacd7dc0d653e5bc424527b5ba39bb0c0e823e/app/react/main.jsx#L57

is this a required route, and is it broken?

**Comment by hannahkane** [comment]
In [this comment](https://github.com/mozilla/science.mozilla.org/issues/100#issuecomment-200990164) we decided to not have a /programs page, so I think that can be removed.

**Comment by alanmoo** [comment]
https://science.mozilla.org/programs/ redirects to the homepage, so I'm closing this.
