### ISSUE TITLE
Projects aren't showing up on events in 'projects' tab

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#477]
No projects? :(

https://science.mozilla.org/programs/events/global-sprint-2016
![screen shot 2016-05-31 at 16 19 15](https://cloud.githubusercontent.com/assets/617994/15689114/74b1099e-274b-11e6-808a-ae56e079a9f9.png)

**Comment by kristinashu** [comment]
This seems like a biggie, particularly since the Sprint starts tomorrow. @alanmoo will you be able to look at this?

**Comment by alanmoo** [comment]
Yeah I'll get it after lunch.

**Comment by kristinashu** [comment]
Cool, thanks!

**Comment by acabunoc** [comment]
sweet, thanks! Australia is coming online in 5hrs
