### ISSUE TITLE
Site won't load in Safari

### ISSUE THREAD

**Issue by stephwright** [mozilla/science.mozilla.org#487]
Have tried on multiple computers.  Works fine in FF but won't load in Safari.  Just get big gray page.

**Comment by gvn** [comment]
Just to be sure, you are loading `https://science.mozilla.org`? It loads in Safari on my machine...

**Comment by gvn** [comment]
Also, what version of Safari?

**Comment by simonwex** [comment]
For what it's worth, it loads fine and functions correctly for me on Safari Version 9.0.3 (10601.4.4).

**Comment by stephwright** [comment]
v 8.0.8 on the first machine we tried... 
v 8.0.5 on second

**Comment by gvn** [comment]
Sounds like Alan has a fix coming...

**Comment by gvn** [comment]
@stephwright Can you try this URL? https://science-mozilla-org-sta-pr-493.herokuapp.com

**Comment by stephwright** [comment]
Getting "no such app" message


On Fri, Jun 3, 2016 at 2:23 PM, gavin lazar suntop <notifications@github.com
> wrote:

> @stephwright <https://github.com/stephwright> Can you try this URL?
> https://science-mozilla-org-sta-pr-493.herokuapp.com
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/issues/487#issuecomment-223697971>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AN8twuz_puczS7OrJd-7hNVx4-raLxJ9ks5qIJs4gaJpZM4Itv58>
> .
>



-- 
Stephanie Wright
--------------------------------------------------------------------------------------
Open Data Training Lead, Mozilla Science Lab
Twitter @shefw  | GitHub @stephwright | Skype: stephanie_4504
ORCID: 0000-0003-3829-318X
"The opposite of 'open' isn't 'closed'.  The opposite of 'open' is
'broken'." ~ John Wilbanks

**Comment by gvn** [comment]
Try http://science-mozilla-org-staging.herokuapp.com/

**Comment by stephwright** [comment]
Success!  Though can only try on the 8.0.8 version... our machine w/ 8.0.5
left

On Fri, Jun 3, 2016 at 2:42 PM, gavin lazar suntop <notifications@github.com
> wrote:

> Try http://science-mozilla-org-staging.herokuapp.com/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/issues/487#issuecomment-223701825>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AN8twkYShvCmOh2QSfLbUTtbBn_feRorks5qIJ-zgaJpZM4Itv58>
> .
>



-- 
Stephanie Wright
--------------------------------------------------------------------------------------
Open Data Training Lead, Mozilla Science Lab
Twitter @shefw  | GitHub @stephwright | Skype: stephanie_4504
ORCID: 0000-0003-3829-318X
"The opposite of 'open' isn't 'closed'.  The opposite of 'open' is
'broken'." ~ John Wilbanks

**Comment by gvn** [comment]
I tried 8 on Saucelabs, so I think it's good.

**Comment by stephwright** [comment]
👍

**Comment by gvn** [comment]
Safari 8 is now working for prod. Closing!
