### ISSUE TITLE
Anchors are good. Let's have some.

### ISSUE THREAD

**Issue by davidascher** [mozilla/science.mozilla.org#492]
It would be good to be able to link to the overview tab in the https://science.mozilla.org/programs/fellowships page, or the FAQ directly, or to an individual's bio. (I in fact wanted to do the last thing yesterday to introduce one of them to a potential partner).

**Comment by alanmoo** [comment]
I thought we had a ticket open, but I guess not- we definitely need to update the tab component to support links, maybe as part of #406.
