### ISSUE TITLE
Set up analytics

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#495]
@alanmoo asked in Chat whether or now we have analytics set up on the new site but I'm not sure. If we don't have them, can we please add it? The old site had them set up.

Google analytics usually doesn't track when someone clicks on an external link on the site but I think there is a way to set that up. This would be valuable to have so we can track stats on the resources.

**Comment by amjadm61** [comment]
Why can't we try the opensource tool [Piwik](https://piwik.org/) instead of google analytics?

**Comment by alanmoo** [comment]
That's an interesting tool to consider, @amjadm61.
It looks like it requires some server-side work, as opposed to simply dropping in a script, so using that might be a bit more work than is needed at this point in time. There's also consistency of data to consider, as with GA we can compare the old site to new pretty easily. Piwik might be something interesting to explore on a new project, or in tandem with Google Analytics for a time.
