### ISSUE TITLE
Move legal language on newsletter sign-up

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#503]
On the newsletter sign-up form in the footer, the line “I’m okay with you handling this info as you explain in your privacy policy” needs to be above the text box, for legal reasons.

**Comment by amjadm61** [comment]
@hannahkane I can create a new PR if this is what in your mind.

![capture](https://cloud.githubusercontent.com/assets/4783625/15963503/2e359182-2f30-11e6-860b-4db6d323b101.PNG)

**Comment by alanmoo** [comment]
Weird. What was the legal concern? You can't submit without checking the box as it is...

**Comment by hannahkane** [comment]
@amjadm61 - thanks for your help with this! Before you submit a PR, I'd like to clarify with our lawyer the exact issue.

@alanmoo - From our lawyer: "The line needs to be above the text box to have real legal value." I interpret that to mean a user could conceivably subscribe to the newsletter before having understood the Privacy Policy. But I do want to clarify the restriction, because I think the design above is potentially confusing as well.

**Comment by alanmoo** [comment]
Yeah, make sure they know the form can't be submitted unless they check the box...this is pretty standard design across the web.

**Comment by hannahkane** [comment]
I haven't heard back yet, but I'm going to kill this ticket. I don't think it's necessary.
