### ISSUE TITLE
Project details - repo preview

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#521]
Repository preview: https://redpen.io/wgdaa9228e6335eb91

- [ ] Add repo preview to django
- [ ] Add to project details page

**Comment by kristinashu** [comment]
@acabunoc I think we had actually decided to remove this feature a while ago, is it ok with you?

**Comment by acabunoc** [comment]
Ah, I vaguely remember that! Yes, that's fine
