### ISSUE TITLE
Events - Add filter for archived events

### ISSUE THREAD

**Issue by kristinashu** [mozilla/science.mozilla.org#522]
https://redpen.io/aq0c17cb0774ab55bd

**Comment by akshatnitd** [comment]
@kristinashu @hannahkane @alanmoo I want to work on this. Can I be assigned to it?

**Comment by alanmoo** [comment]
What's your plan for this? The UI should be pretty easy to implement, but what's it filtering based on? Do the different events already have tags you can use to filter?

**Comment by akshatnitd** [comment]
@alanmoo Yes, the UI can be easily implemented. Based on this https://redpen.io/aq0c17cb0774ab55bd , the filtering is based on the type of event. For that the /events API should return either the type of event, or we can do filtering based on the dates. If the API is made to return the event category, then we can also make the Additional notes's link label dynamic, inplace of ''ETHERNET LINK".

**Comment by alanmoo** [comment]
So this is blocked by the API then. That work should be done first.

**Comment by akshatnitd** [comment]
@alanmoo The API issue has now been solved. Please review it.
