### ISSUE TITLE
Link broken on Fellowships page

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#528]
### Context

The overview text on the science site for the programs/fellowships page has a section with a "read more [here]() that currently links to the same page. 

![screen shot 2016-07-09 at 1 03 50 pm](https://cloud.githubusercontent.com/assets/1559703/16709138/f0f1e5c0-45d5-11e6-9449-a2df50715892.png)

### Expected Result
The link directs the user to the FAQ, where we answer some possible questions in depth.

### Current Result
The link reverts to the same page. 

### Suggestions 

*some ideas in order of preference* 

* [ ] we find a way to reference the FAQ in the URL (maybe there is already a way to do this!), right now : https://science.mozilla.org/programs/fellowships#faq does not paginate to the FAQ page
* [ ]  I create something in a gist that we can link to with specific FAQ info relevant to visas/finance
* [ ] we redirect the link to the Ask-Us-Anything etherpad where we answer more questions: https://public.etherpad-mozilla.org/p/2016-fellowship-ama
* [ ] we just remove the link

Happy to help with either or a different solution in a PR, just let me know what you'd prefer by checking the right box above. Ideally, I'd fix this on Monday, as they'll have only one more week to apply for the fellowships.

cc @kaythaney as this pertains to your emailed question, @acabunoc

**Comment by acabunoc** [comment]
This opens the FAQ tab for me. What browser/OS are you on?

**Comment by acabunoc** [comment]
Firefox Developer Edition 49.0a2 (2016-07-05)
OSX 10.9.5
![fellowship](https://cloud.githubusercontent.com/assets/617994/16709244/f040b522-45d8-11e6-8532-b08d93338304.gif)

**Comment by auremoser** [comment]
OS 10x El Capitan
Firefox 47.0.1
![screen shot 2016-07-09 at 1 35 46 pm](https://cloud.githubusercontent.com/assets/1559703/16709277/ce06db70-45d9-11e6-994d-6acad3364b7c.png)

Oh weird, the url: https://science.mozilla.org/programs/fellowships#. Doesn't work in Safari or Firefox or Chrome on mine (see gif below), but does work when you click the link on the home page (see gif below where the link directs to the faq but reload of that same link doesn't). Not sure why. 

Chrome 51.0.2704.103:
![fellows](https://cloud.githubusercontent.com/assets/1559703/16709302/7f357438-45da-11e6-996f-572017e33f15.gif)

So maybe the issue isn't that the link doesn't work in the overview page, but rather the link doesn't exist to the FAQ if you're not moving directly from that hyperlink.

##### new issue
It would be cool to have a persistent link that I could point to in emails, so if I need to reference the FAQ, this link would do that: https://science.mozilla.org/programs/fellowships#.

Aurelia

**Comment by acabunoc** [comment]
ah persistent links are live on on develop, but are not on production yet. See original issue for this here:
https://github.com/mozilla/science.mozilla.org/issues/492

**Comment by acabunoc** [comment]
On production, current link switches tabs with JavaScript on click, so there's no anchors to tabs directly

**Comment by alanmoo** [comment]
This should technically work now after a deploy, though I still want to convert the `<a>` tag to a `<Link>` so the whole page site doesn't get reloaded.

**Comment by auremoser** [comment]
Sounds good, close when ready, thanks @acabunoc

On Mon, Jul 11, 2016 at 11:50 AM, Alan Mooiman <notifications@github.com>
wrote:

> This should technically work now after a deploy, though I still want to
> convert the <a> tag to a <Link> so the whole page site doesn't get
> reloaded.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/issues/528#issuecomment-231776893>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABfMl2RmwioU_rhPdJDXbDkwCYDB0dC7ks5qUmZfgaJpZM4JIqIu>
> .
>



-- 
Aurelia Moser
Community Lead, Mozilla Science Lab
Twitter @auremoser | GitHub @auremoser | Skype: auremoser1

**Comment by acabunoc** [comment]
@auremoser you should be able to link to https://science.mozilla.org/programs/fellowships/faq now! closing

**Comment by auremoser** [comment]
Thank you!

On Mon, Jul 11, 2016 at 12:00 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Closed #528 <https://github.com/mozilla/science.mozilla.org/issues/528>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/science.mozilla.org/issues/528#event-718928957>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABfMl1myHXwhXWuyTkmLP6FEaDRsTckVks5qUmiogaJpZM4JIqIu>
> .
>



-- 
Aurelia Moser
Community Lead, Mozilla Science Lab
Twitter @auremoser | GitHub @auremoser | Skype: auremoser1
