### ISSUE TITLE
Blog not loading for @kaythaney

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#529]
Firefox 47
OSX 10.11.2

Just says 'Latest News' and nothing underneath :(

**Comment by alanmoo** [comment]
@kaythaney I just deployed to production, please force refresh and see if it's still happening.

**Comment by kaythaney** [comment]
still nothing, sadly. :(

**Comment by hannahkane** [comment]
Is this still an issue?

**Comment by alanmoo** [comment]
I believe it was a browser plugin, right @kaythaney?

**Comment by kaythaney** [comment]
Yep! Can be closed.

sent on the move. apologies for typos.
