### ISSUE TITLE
Close fellows application

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#532]
The Fellows application is now closed! 

Can we:
- [x] Hide the 'apply to be a fellow' hero images on the homepage
- [x] Hide the 'Apply Now' button on https://science.mozilla.org/programs/fellowships
- [x] Hide the 'Apply Now' block at the bottom of https://science.mozilla.org/programs/fellowships

**Comment by acabunoc** [comment]
Should be pretty similar to https://github.com/mozilla/science.mozilla.org/issues/374

**Comment by hannahkane** [comment]
@alanmoo - can we assign this to you as part of Go Global team?

**Comment by alanmoo** [comment]
Yeah I can take care of this first thing tomorrow.
