### ISSUE TITLE
2016 Fellows Page

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#537]
cc: @stephwright @hannahkane @kristinashu 

### Context

We'll be announcing the 2016 fellows this Friday (or possibly Monday), and I'd like some design advice about how to structure the fellows page/tab to appropriately showcase alumni and current fellows. I'll have the content (bios and photos with appropriate proportions) today, EOD.

### Question
1. Should the 2016 fellows fall in the same /fellows/ tab, and copy the format/sit on top of the 2015 fellows? Or should there be a place for Alumni and a place for Current fellows (i.e. separate tabs?).
2. Where should this happen? I imagine the github repo is the best place to make these changes, as photos will need to be added here and the Django interface isn't for these kind of annual updates. Is that something I am allowed to do or should I ask for help from a production team member, and if the former, what branch should I push to and who do I assign for QA? 

[This the the tab/page](https://science.mozilla.org/programs/fellowships/fellows) I'm talking about:

![screen shot 2016-09-08 at 10 43 28 am](https://cloud.githubusercontent.com/assets/1559703/18353421/e4d4e5a8-75af-11e6-9f08-e55b298fd1c2.png)

Apologies for all the questions, I just don't know the protocol and want this to be smooth.

### Suggested solutions
*check the one you think is best or just reply below please*

* [ ] I'm inclined to just copy the formatting and push the new fellows/content to the same tab...the scroll would be a little long but it won't disrupt the design substantially
* [ ] We could also do the "current" and "alumni tabs, adding a 4th tab to the current 3, but that might be more trouble than it's worth and it doesn't have the same intuitive information architecture.

### Deadline

I'd like to take care of this by Friday 9/9/16, or Monday 9/12/16, as that's when we'll be making the announcement.

**Comment by kristinashu** [comment]
Such a clear and thorough ticket! 

For question 1: I'm inclined to just copy the formatting and push the new fellows/content to the same tab. Since there are only 4 fellows and their bio's are nice and short, I think the page length will be just fine.

For questions 2: @alanmoo or @gvn might have better insight?

**Comment by hannahkane** [comment]
Sorry to be so late to this! I see you've added a PR, @auremoser, which looks great. Let me know if you need anything else.

**Comment by alanmoo** [comment]
Looks like this is live, still any open questions for me or can we close this issue?

**Comment by auremoser** [comment]
Yes, close-away. Thanks so much everyone, I asked @acabunoc to escalate it and push this morning. Thanks, closing.
