### ISSUE TITLE
dropdown menu size is small so characters are not visible properly

### ISSUE THREAD

**Issue by Ghusar** [mozilla/science.mozilla.org#539]
go to https://science.mozilla.org/projects and scroll down to "Contribute to a Project". 
There dropdown menu  height is less than search box size so characters are not visible properly
![screenshot from 2016-09-12 21-52-25](https://cloud.githubusercontent.com/assets/15612246/18443788/23872e8c-7934-11e6-9d4e-ab45dbb80a4d.png)

**Comment by alanmoo** [comment]
I can't seem to reproduce this, even on Chromium 52 in Linux. What version of Chrome are you using @Ghusar?

**Comment by Ghusar** [comment]
i have  used google chrome in linux not chromium
