### ISSUE TITLE
Site doesn't work in Safari 8

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#541]
Or older browsers in general...may need a polyfill or something.

**Comment by Pomax** [comment]
Which one does Apple officially still support, and how many users are impacted?

**Comment by alanmoo** [comment]
Safari 9 is current. Not sure how many but I've identified the problem and am working on it.

**Comment by Pomax** [comment]
had to look it up, 8 was OSX 10.10 which I *think* is still a valid target.
