### ISSUE TITLE
Search / Filter blog posts

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#546]
@kristinashu - do we have designs for this?
- [ ] Post list: Search
- [ ] Search results view
- [ ] Post list : Filter results

**Comment by hannahkane** [comment]
Estimate (5) is for implementation only. If design work is needed, we'd add to the estimate.

**Comment by hannahkane** [comment]
@kristinashu - would this be the relevant design work? https://redpen.io/ng651dee79aa4a00d0

**Comment by kristinashu** [comment]
That's the relevant work but I didn't mock up the screens mentioned above. Styling could be similar to https://redpen.io/yf7847e3d9ec2ff2b3

**Comment by arush0311** [comment]
Can I take this?

**Comment by kristinashu** [comment]
@arush0311 thanks for offering to help but building this search and filter functionality is a large amount of work and probably not suitable to do at this time.

**Comment by arush0311** [comment]
@kristinashu I agree, but I still wanna try it out. If I find difficulty I will unassign myself.
> probably not suitable to do at this time.

Why is that?

**Comment by kristinashu** [comment]
@alanmoo are you able to elaborate on what the steps would be?

**Comment by alanmoo** [comment]
@arush0311 feel free to give it a shot but you're going to have to do some digging in issues and such to figure out what actually needs to be done. I think the Wordpress API we use will allow you do do these searches and such, but I'm not positive.

**Comment by arush0311** [comment]
please review :)
