### ISSUE TITLE
Add helper text to "Short Description" and "Description" fields on Events admin

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#549]
From @auremoser: It would be nice to have some small grey text explaining the difference between Short Description and Description in terms of where they fall on the page and whether they should be redundant because they display in different places, or not because they display one after another

**Comment by hannahkane** [comment]
@auremoser - could you please provide copy that would be the most useful to you?

**Comment by auremoser** [comment]
Maybe:

Short Description:
> This appears below the photo in the card pre-view, and below the title in the full-page view

Long Description
> This appears below the photo in the full-page view; should be distinct from the "short description" 

I'm happy with edits on either. Feel free to ignore it too; when I wrote that, I found it confusing, but it didn't take long to learn, so it's o.k.

**Comment by akshatnitd** [comment]
@auremoser Please review it. Made the changes :+1:

**Comment by auremoser** [comment]
Thank you @akshatnitd !
