### ISSUE TITLE
Make it easier to add facilitators to an event

### ISSUE THREAD

**Issue by hannahkane** [mozilla/science.mozilla.org#550]
Adding facilitators to an event is hard since you can't sort all the people. They appear in a giant list in the order they were created.

Let's discuss possible solutions and which would be best:
 * Sort by alpha
 * Sort by [something else]
 * Add search
 * Allow user to start typing a name, and auto-complete

**Comment by hannahkane** [comment]
@auremoser and @acabunoc - can you weigh in on the desirability of the solutions? And feel free to add other ideas.

@gideonthomas - can you offer insight into implementation details?

**Comment by auremoser** [comment]
I think typing a name and having it auto-complete or auto-filter the options below would be great, but alpha sort is a good first-pass fix. I vote for Alpha sort.

This implies also building a view/template to display facilitators though, and maybe that's something we'll push to the auth work in the next phase?...would the event creator always be the one manually adding facilitators and participants? Or did we want to wait until they can add themselves, if that's on the agenda?

**Comment by hannahkane** [comment]
Didn't realize this was a dupe of #424. Going to close this, though @auremoser's question about who will be adding people is important. I think that will likely come up in the Science team's strategy planning session Oct 10-13.
