### ISSUE TITLE
Migrate to wp-api v2 on blog

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#558]
It's probably best to do this so that we have better support in the future.

@acabunoc @auremoser do you know what else is using the blog api that might be affected by this change?

**Comment by acabunoc** [comment]
just the blog & rss feed (which I think is not working right now)

**Comment by auremoser** [comment]
+1 to @acabunoc , pretty sure that's it.

**Comment by alanmoo** [comment]
Dupe of #346
