### ISSUE TITLE
COC Page

### ISSUE THREAD

**Issue by belkinsa** [mozilla/science.mozilla.org#56]
Looking at the pages of the site, there is a coc.jade page which isn't being linked anywhere.  I think it should unless it's only for new users when they join the site.  Even if it's that, I think it should be linked somewhere viable for everyone to see.

**Comment by acabunoc** [comment]
It's in the footer on each page, but thanks @belkinsa! Happy to move it more central

**Comment by belkinsa** [comment]
Do you have any suggestions on where because I looked and it looks like there is no good place for it to be central, unless it's a menu item?
