### ISSUE TITLE
fellows pictures are improperly styled

### ISSUE THREAD

**Issue by HassenPy** [mozilla/science.mozilla.org#576]
the fellows page has weird styling on the fellows pictures
![2017-03-01-184930_1366x768_scrot](https://cloud.githubusercontent.com/assets/7109776/23473328/162b8a2e-feb0-11e6-9ea9-1c09e9de9a7e.png)
i think they were meant to look like the ones on the people page.

**Comment by alanmoo** [comment]
What browser are you using?

**Comment by HassenPy** [comment]
oh, forgot to mention that, Chrome Version 48.0.2564.116 on ubuntu

**Comment by HassenPy** [comment]
that version of chrome is not supported anymore, works well on firefox.

**Comment by alanmoo** [comment]
Ok, then closing this

**Comment by HassenPy** [comment]
maybe this should have the same styling as the people's page for consistency?

**Comment by alanmoo** [comment]
Yeah, it would be best if they were a shared react component, and `fellows` used sizing similar to `people`. Feel free to open a new issue for that if you'd like.
