### ISSUE TITLE
Broken link in /programs/studygroups -Internet

### ISSUE THREAD

**Issue by rahulkrishnan98** [mozilla/science.mozilla.org#591]
![moz7](https://cloud.githubusercontent.com/assets/20839638/23612227/8e6fd3b6-02a0-11e7-902f-56aa62127f58.png)
 
The Internet study group points to a broken link.

**Comment by rahulkrishnan98** [comment]
There are other broken links on the same page aswell.

**Comment by rahulkrishnan98** [comment]
@auremoser

**Comment by auremoser** [comment]
Done, removed, thank you @rahulkrishnan98 !
