### ISSUE TITLE
Add event type to event view in API

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#592]
Related to #522 and possibly others, events have a type, which should be exposed by the API. @acabunoc do the categories in #522 cover the needs?

**Comment by akshatnitd** [comment]
@alanmoo @acabunoc Can I work on the API part also? How can I get access to the API code?

**Comment by akshatnitd** [comment]
@alanmoo @acabunoc I am proceeding by adding a new field 'type' in the events model, and then sorting can be done on that basis. Is that the correct way?
