### ISSUE TITLE
 Text breaks the flex at mid view-ports 

### ISSUE THREAD

**Issue by rahulkrishnan98** [mozilla/science.mozilla.org#593]
![moz8](https://cloud.githubusercontent.com/assets/20839638/23624179/dbc6ef6c-02ca-11e7-9059-758fb849e75d.png)
 
@auremoser  I am working on this. 
Should It be made to show only one div element( the data-card-wrapper) or should I decrease font size at that specific view-port. If you have another work-around, will implement it.

**Comment by auremoser** [comment]
Cool, thank you @rahulkrishnan98 , let me know when you'd like a review!
