### ISSUE TITLE
Sub-menu drop on mouse hover

### ISSUE THREAD

**Issue by KameyHameyHa** [mozilla/science.mozilla.org#596]
Sub-menu drop down of 'Programs' on mouse hover

**Comment by alanmoo** [comment]
Can you give some more details on this? For example, What's it doing vs. what should it be doing? Browser version/platform?

**Comment by KameyHameyHa** [comment]
The 'Programs' option on the main header menu should be clicked before the submenu containing 'Our Events','Study Groups' and 'Fellowships' is displayed. 
![image](https://cloud.githubusercontent.com/assets/19530299/23949852/e79b29ee-09ae-11e7-9819-0c1d7f8a1490.png)
![image](https://cloud.githubusercontent.com/assets/19530299/23949882/0d1e5434-09af-11e7-9dde-ec687a498b30.png)

It would provide smooth and clear website navigation.

**Comment by dhiraj161298** [comment]
@KameyHameyHa IMHO I find the current setup more elegant and efficient. Also having a hover menu has its own problems such as the submenu doesn't stick in case the mouse is out of position which results in bad UX.

**Comment by alanmoo** [comment]
Agreed, triggering a menu on hover is a UX concern. Thanks for your suggestion, though we've had UX conversations about many of these types of things in the past. This project is mostly at a "file a bug if something is clearly broken" state, other than when stakeholders request changes.
