### ISSUE TITLE
Make the clickable links distinguishable from the headings in the dropdown navbar

### ISSUE THREAD

**Issue by akshatnitd** [mozilla/science.mozilla.org#599]
In the screenshot, 'Programs' is not a link, but just a heading which should be distinguishable from the other links which are clickable. The color maybe changed for better UX.

 ![deepinscreenshot20170323122936](https://cloud.githubusercontent.com/assets/12656846/24235702/7df9d230-0fc4-11e7-89c5-6398e5aa6d28.png)

**Comment by akshatnitd** [comment]
How about this as a solution?

![deepinscreenshot20170323124000](https://cloud.githubusercontent.com/assets/12656846/24235993/e353e0d4-0fc5-11e7-84de-46083a8736fc.png)

**Comment by alanmoo** [comment]
I like this, @kristinashu what do you think?

**Comment by kristinashu** [comment]
Looks good to me!

**Comment by akshatnitd** [comment]
@alanmoo @kristinashu Sent the PR :+1: 

The screenshot looks like this.

![deepinscreenshot20170413110934](https://cloud.githubusercontent.com/assets/12656846/24991628/e20c9bce-2039-11e7-98f0-b1b207c27751.png)
