### ISSUE TITLE
Migrate React Components to ES6 syntax

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#613]
React 15.5 signals the imminent deprecation of the `React.createClass` method (moving it to a separate component). In the interest of staying up to date, it would be great if we can update our components to use the ES6 syntax. This doesn't have to happen all at once (in fact, it would be easier to test if it doesn't), but if anyone wants to help out, they can update a component and open a PR. Just drop a comment in this issue before starting so you don't end up duplicating effort (don't wait for someone to tell you to go ahead though, just start).

[This post](https://toddmotto.com/react-create-class-versus-component/) seems to give a good overview of the differences between the syntaxes.

**Comment by HassenPy** [comment]
i ll start with the component i added, should similar work be done to mofo-ui?

**Comment by akshatnitd** [comment]
@alanmoo Sure, I am up for it. Should I go ahead and do it component wise?

**Comment by alanmoo** [comment]
Yeah. Can you start by making a checkbox list of all the components so that we can check them off here as they get done and no one doubles up on work?

**Comment by akshatnitd** [comment]
@alanmoo Yes, sure. Making it.

**Comment by akshatnitd** [comment]
### The components/pages to be migrated to ES6 syntax
**Components :** 
- [] Events
- [] Events
- [] Events
- [] Events

**Comment by akshatnitd** [comment]
### The components/pages to be migrated to ES6 syntax
**Components :** 
- [] Categories
- [] Data-Card
- [] Event List
- [] Footer
- [] Github Avatar
- [] Greeting
- [] Header
- [] Profile-Card
- [] Project-Card Featured
- [] Project List
- [] Tab Switcher
- [] Three-Up
- [] User List

**Pages :** 
- [] Blog Post
- [] Code of Conduct
- [] About event
- [] Event details
- [] Fellowships
- [] Home
- [] Project Details
- [] Projects
- [] Resources
- [] Project List
- [] Study Groups
- [] Join Study Groups
- [] Run Study Groups
- [] Blog
- [] Event
- [] People
- [] Style Guide
- [] Main

**Comment by akshatnitd** [comment]
Completed the blog component. Sent the PR.
Working on the Blog Post component.

**Comment by akshatnitd** [comment]
Working on the Categories, Data-Card, Event List, Footer, Icon and GithubAvatar component. Will send the PR once #620 gets merged !

**Comment by alanmoo** [comment]
@akshatnitd Github automatically closes an issue when a PR with "Fixes #xxx" or "Closes #xxx" gets merged. Let's avoid that for these components for now. Something like "See #613" should be fine.

**Comment by akshatnitd** [comment]
@alanmoo Okay cool :+1: Shall be using 'See #613' !

**Comment by akshatnitd** [comment]
@alanmoo Made the migrations for all the components. Will be doing the migrations for the pages next-up :)
