### ISSUE TITLE
Close fellows' application ASAP

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#632]
The Fellows application is now closed (as of May 14th, and I'm late logging this issue)! 

Can we:
- [ ] Hide the 'apply to be a fellow' hero images on the homepage
- [ ] Hide the 'Apply Now' button on https://science.mozilla.org/programs/fellowships
- [ ] Hide the 'Apply Now' block at the bottom of https://science.mozilla.org/programs/fellowships

Should be similar to #374 +  #532 

Thank you!

**Comment by arush0311** [comment]
please review :)

**Comment by auremoser** [comment]
I left a comment about adding `hidden` to some of the divs, but +1 to adding the `h3` "this application is now closed"

**Comment by alanmoo** [comment]
This is merged and live but I've noticed "The call closes May 14, 2017 at 11:59PM EDT." is still on the page. Should that be removed too?

**Comment by auremoser** [comment]
Good catch, yes it should be removed.
