### ISSUE TITLE
Banner at bottom of fellowship page is off center

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#636]
At large screen sizes, the text "The 2017 call for applications is now closed" at the bottom of https://science.mozilla.org/programs/fellowships is off center. We should update the markup so that it uses appropriate bootstrap grid classes (`container`, `row`, `col-xx`)

@arush0311 This wasn't a result of your latest PR, but could you take a look at this?

**Comment by arush0311** [comment]
sure!
