### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by arush0311** [mozilla/science.mozilla.org#639]
- [ ] enable HTTP2.
- [ ] enable server push
- [ ] optimize images
- [ ] uglify css
- [ ] ~~research brotli compression~~

Anything else that improves on performance, please add to the list.
ping @alanmoo @gvn @gideonthomas

**Comment by alanmoo** [comment]
Can you clarify what you mean by "server push"?

**Comment by arush0311** [comment]
https://www.smashingmagazine.com/2017/04/guide-http2-server-push/. In general its sending content which client did not explicitly request for, like sending style.css also when client  request for index.html

**Comment by gideonthomas** [comment]
I would suggest gzip instead of brotli so that we standardize across our apps

If you file individual issues for this, I can enable HTTP 2.0
