### ISSUE TITLE
Add city column to study group admin view

### ISSUE THREAD

**Issue by alanmoo** [mozilla/science.mozilla.org#644]
For the admin view of the study groups, we're sorting by city name but it's hard to read as currently structured. Can we add a column to display the country (or city? Not sure about the formatting of the data) name so it's easier to visually scan? And another column for region?

See: https://github.com/mozilla/science.mozilla.org/issues/424#issuecomment-306438773

**Comment by YoyoAnandra** [comment]
Hi, there ! I wanted to participate in GSOC, so wanted to contribute to this project will it work, what should i do..

**Comment by alanmoo** [comment]
Hi, thanks for your interest but we won't be running GSoC for this project this year.

**Comment by YoyoAnandra** [comment]
Can u suggest me any project for GSOC 2018.

**Comment by alanmoo** [comment]
I don't believe projects have been submitted yet by host organizations, so I'm not sure, sorry.

**Comment by YoyoAnandra** [comment]
Anyways Thank you Sir.

**Comment by algomaster99** [comment]
Hey! I am new to the open source community and would like to contribute to this issue. How can I go about?

**Comment by alanmoo** [comment]
Hi @algomaster99, thanks for the offer but this repo isn't really maintained anymore. If you're looking for something to help on, check out https://github.com/mozilla/foundation.mozilla.org.

**Comment by algomaster99** [comment]
Thanks @alanmoo !
