### ISSUE TITLE
Update on Science Fellows 2017 bios

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#654]
cc: @stephwright @hannahkane @kristinashu @community-impact

### Context
We'll be announcing the 2017 fellows this Friday (or possibly Monday), and I'd like to update their bios on our website among the other fellows. I'll have the content (bios and photos with appropriate proportions) today, EOD.

### Plan
I'm planning to update the [Fellows page](https://science.mozilla.org/programs/fellowships/fellows) with this info and pairing it with a blog post, and I just want to check that we're keeping the same format as last year (just chaining the bios with the preceding fellows' bios and not making a new page, per #537 from last year. 

I can submit this as a PR this week and ping Alan for merge, but just wanted to check:
* [x] that I'm not missing anything (design changes, suggestions, image size/prep issues)
* [x] that this is still the site we should update or whether there's an appropriate page on the Network Site I should also update
* [x] that there are no new issues or feature updates I'll need to consider per our recent GSOC students contributions cc/ @alanmoo 

Feel free to check any that apply above or reply on this thread!

### Deadline
I'd like to take care of this by **Friday 9/8/17**, or **Monday 9/11/17**, as that's when we'll be making the announcement.

Thank you so much!

**Comment by hannahkane** [comment]
Thanks, @auremoser. I don't have any concerns about you updating this content. See [my comment](https://github.com/mozilla/network/issues/715#issuecomment-327268270) on the Network site ticket for my opinion on your second question.

**Comment by alanmoo** [comment]
Sound good to me

**Comment by auremoser** [comment]
Closing this issue as the site is live.
