### ISSUE TITLE
Routing broken for Events page

### ISSUE THREAD

**Issue by auremoser** [mozilla/science.mozilla.org#656]
cc / @stephwright + @acabunoc 

## Context

When we have new "events," anything from a Community Call to a working open workshop, I update the event details in our Django admin and then the events post to our website here: https://science.mozilla.org/programs/events. 

## Current Result
Today I posted two events, a community call for October 12th and a Study Group Call for October 6th and neither is populating on our site under "Our events". 
![screen shot 2017-09-12 at 11 55 30 am](https://user-images.githubusercontent.com/1559703/30335831-5b424e0a-97b1-11e7-9ba2-fea407ac7e28.png)

I see there's a "Community Call April test" event as the first in the "Past Events" on that page, so I imagine someone has noticed this and is testing it, but I've double checked the dates and times and something must be wrong with the routing from django to our website.

![screen shot 2017-09-12 at 11 55 39 am](https://user-images.githubusercontent.com/1559703/30335828-57c634c6-97b1-11e7-8352-1afcb5c96035.png)

## Expected Result
Normally, as soon as I update an event in Django, it populates on our website on page refresh, usually as a card under "Our Events" and only under "Past events" when I accidently do the date wrong.

Any help would be stellar. Thank you!

**Comment by hannahkane** [comment]
cc'ing @gideonthomas since @alanmoo is out today

**Comment by gideonthomas** [comment]
Uh-oh....it looks like it's getting its data from the wrong API (it's using staging data not production data). Let me look into it

**Comment by gideonthomas** [comment]
Looks like the last deploy was done using the "promote to production" button instead of a manual deploy on heroku - which seems to have been the issue.

@auremoser, should be working now (you might need to refresh the page/clear cache)

**Comment by auremoser** [comment]
Amazing @gideonthomas thank you so much! Closing the issue now!

**Comment by alanmoo** [comment]
Ugh, sorry about this. Was manual deployment always the requirement for the science site? (We're talking front end, not API, right?)
