### ISSUE TITLE
close form for new study groups

### ISSUE THREAD

**Issue by acabunoc** [mozilla/science.mozilla.org#665]
Can we close the form for new study groups?

cc: @stephwright @alanmoo

**Comment by acabunoc** [comment]
The one on this page: https://science.mozilla.org/programs/studygroups/run

**Comment by acabunoc** [comment]
I think so, I'll let @stephwright confirm

**Comment by stephwright** [comment]
Yep... that's all we need from our side for now.  We are transitioning ownership of the Study Groups to the Carpentries and this whole page will go away (in some fashion - logistics & content TBD) but for now, we just need folks to stop requesting to start new ones.
