### ISSUE TITLE
Collaborate: moving projects breaks site

### ISSUE THREAD

**Issue by gedankenstuecke** [mozilla/science.mozilla.org#79]
Hey there,
we've [moved our repository for openSNP into an organization lately](https://github.com/openSNP/snpr), but the links on collaborate are still pointing to the old location, [breaking the site](https://www.mozillascience.org/projects/gedankenstuecke-snpr). 

As I can't access the site I'm unable to fix the links. Help, pls? :smiley:

![pussinboots.gif](http://media0.giphy.com/media/abZ5exGrse0W4/giphy.gif)

**Comment by gedankenstuecke** [comment]
So, the hotfix for this on the user end: I forked the repo back into my userspace, so at least a fork was available on the old URL, then I could log in to MSL collaborate and change the URL to the new one, not the most elegant solution but at least it's back up and running :)

**Comment by auremoser** [comment]
Oh no I'm sorry! Thanks for the hot-fix. The kitten gif is heartbreaking.

**Comment by gedankenstuecke** [comment]
Not sure how to fix the issue itself though. Because even without me doing the fork of the repo the old URL https://github.com/gedankenstuecke/snpr was still redirected by GH to the new one at https://github.com/openSNP/snpr. 

So maybe you could just allow redirects on your end?

**Comment by acabunoc** [comment]
This is heartbreaking! 

Not sure what happened though -- when you say 'breaking the site' do you have a screenshot? Did you get an error, or were certain parts of the page missing?

Glad you were able to find a fix in my absence!

**Comment by gedankenstuecke** [comment]
Sorry, I didn't do a screenshot, but the website just give an error message, probably from whatever framework is powering it. And afterwards the site was completely unavailable for me for a couple of minutes. Shall I try to reproduce it?

**Comment by acabunoc** [comment]
That helps! I can probably repo on my end -- thanks for the info :)

**Comment by gedankenstuecke** [comment]
Great, let me know if you need help anywhere :)

**Comment by acabunoc** [comment]
closing! old site
